<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PayNet</name>
   <tag></tag>
   <elementGuidId>c8764e90-507c-4360-8829-2ddf8a43e2ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='B2C']//descendant::img[@title=&quot;SBI Bank A&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>6801a4f1-700c-4628-83cf-bfc268f69404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1736738087189</value>
      <webElementGuid>bd2709be-d763-4d67-bdbb-d18266508be0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
