<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Single Rider Or Agreed Value</name>
   <tag></tag>
   <elementGuidId>7e4b5da4-8456-4c3f-93e6-9a8f134bca8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@for='sum-insured-type-agreed-value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>638df266-ca3c-42b8-b38f-496a7ffe92df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1736738258801</value>
      <webElementGuid>ff74d38b-e2cc-4240-8c24-63254b4db504</webElementGuid>
   </webElementProperties>
</WebElementEntity>
