<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Motorcycle Details View</name>
   <tag></tag>
   <elementGuidId>bafdad7c-6f10-4f5e-8ddc-46460d373665</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(text(),'${detail_text}')]//ancestor::div[@class='card-body']//descendant::a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>1b9532be-2156-4238-881d-752e1dc639dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1735549555474</value>
      <webElementGuid>9000e0b2-457a-404a-940f-15fe247cdbe1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
