<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dybutton_nationalitySelection_quotation,quotationType</name>
   <tag></tag>
   <elementGuidId>b0e4c8ba-347c-4f91-af54-b5c58e715224</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[contains(@class, 'form-label') and contains(text(), &quot;${quotation}&quot;)]//following-sibling::*//following::a[contains(text(), &quot;${quotationType}&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>39f579e3-83d6-43d8-898f-6379a82e738c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1743645654203</value>
      <webElementGuid>aa1be791-c276-4ebb-9832-ea5495ef18d9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
