<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_dateOfBirth</name>
   <tag></tag>
   <elementGuidId>43b98c03-47cf-4f80-b447-c6f61f6b11be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='personalDetails.dateOfBirth']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;personalDetails.dateOfBirth&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;E.G. : 25/03/1997&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7cad61a-f3f3-40d9-89d2-2dfdeb7ac593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>b011b13f-94f3-430e-981c-ff663f372030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>E.G. : 25/03/1997</value>
      <webElementGuid>2ad35cb9-3df3-4848-a24b-2ba9ab0911a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personalDetails.dateOfBirth</value>
      <webElementGuid>17053544-aabb-4dac-9d78-b72d30954ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3c68acf5-e0f8-4a5f-9a0f-b6819978405e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextInputV2__FormControl-sc-1yhoudg-0 iTxspb undefined undefined form-control</value>
      <webElementGuid>d0a9a5b9-443b-44d1-a15c-b45ba8a9bd3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;layout__Styles-sc-csgnm7-0 iJzkTS&quot;]/div[@class=&quot;quotation__Styles-sc-1i79f2c-0 izxPpS bg-white&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;first-form row&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;QuoteForm__Styles-sc-fhdaqy-0 eXPZRQ shadow p-3 rounded bg-body-tertiary&quot;]/form[1]/div[@class=&quot;justify-content-center gap-3 mb-4 row&quot;]/div[@class=&quot;col-md-4&quot;]/div[1]/div[@class=&quot;input-group&quot;]/input[@class=&quot;TextInputV2__FormControl-sc-1yhoudg-0 iTxspb undefined undefined form-control&quot;]</value>
      <webElementGuid>a02abd1c-6439-43ef-89e7-9ab0487590ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='personalDetails.dateOfBirth']</value>
      <webElementGuid>e5861f9f-922a-425f-b2c2-ed4d363cfcb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/div[2]/div/div/div/form/div[3]/div[4]/div/div/input</value>
      <webElementGuid>2bed1442-29a6-4333-9a1b-5146802030e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>398bcb93-1f4f-4094-b120-ff5d8201617c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'E.G. : 25/03/1997' and @name = 'personalDetails.dateOfBirth' and @type = 'text']</value>
      <webElementGuid>ae03312c-257c-40f1-85c8-6b83297349d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
