<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IDNumber</name>
   <tag></tag>
   <elementGuidId>f72244b7-e480-4a3f-9d1c-4a6b3ee36042</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='personalDetails.idNumber2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;personalDetails.idNumber2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;EG : RF/123456&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>728f5abd-e5c1-4611-8162-84fc911835bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>634bbcc3-64b2-46d3-b5b0-580b5c01e2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personalDetails.idNumber2</value>
      <webElementGuid>10bba3c8-62f7-49c3-94e6-9b82281ee0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>EG : RF/123456</value>
      <webElementGuid>4f5d445c-077b-44fe-bfcb-798a0e385352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0c237b00-97cf-45a9-81fa-f759d5cda15d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextInputV2__FormControl-sc-1yhoudg-0 iTxspb border border-danger undefined form-control</value>
      <webElementGuid>1d79f636-a50c-4e44-b219-083904c64449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;layout__Styles-sc-csgnm7-0 iJzkTS&quot;]/div[@class=&quot;quotation__Styles-sc-1i79f2c-0 izxPpS bg-white&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;first-form row&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;QuoteForm__Styles-sc-fhdaqy-0 eXPZRQ shadow p-3 rounded bg-body-tertiary&quot;]/form[1]/div[@class=&quot;justify-content-center gap-3 mb-4 row&quot;]/div[@class=&quot;col-md-4&quot;]/div[1]/div[@class=&quot;input-group&quot;]/input[@class=&quot;TextInputV2__FormControl-sc-1yhoudg-0 iTxspb border border-danger undefined form-control&quot;]</value>
      <webElementGuid>e49bd40b-d0d0-49d1-88d3-5f35edbf0dba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='personalDetails.idNumber2']</value>
      <webElementGuid>8443bdaa-5df5-4af6-adcb-429bf8b5b46d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/div[2]/div/div/div/form/div[3]/div[3]/div/div/input</value>
      <webElementGuid>54200c9b-24ea-4dd8-887f-0be55ab6141b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>31217179-3bc5-43e8-98ee-77ca0dc9de3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'personalDetails.idNumber2' and @placeholder = 'EG : RF/123456' and @type = 'text']</value>
      <webElementGuid>5d2e5282-52e6-48bf-a2d7-18dee98643fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
