<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_chasissNumber</name>
   <tag></tag>
   <elementGuidId>05df0b20-e87d-466a-bbe1-2e01273e5adb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='vehicleDetails.chassisNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;vehicleDetails.chassisNumber&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Type in your car chassis number&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3d8a29e-b37a-468f-9ba0-f7e64f0a35a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type in your car chassis number</value>
      <webElementGuid>c7893ca5-06c9-4551-ba23-66303dcf34a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vehicleDetails.chassisNumber</value>
      <webElementGuid>5c13a5af-f1a8-4bca-b2c4-f680c8957051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b7be075f-f6bd-4990-8009-9687db036ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextInputV2__FormControl-sc-1yhoudg-0 fmqRdx undefined undefined form-control</value>
      <webElementGuid>48d926c1-dac7-4e0e-982d-bfa6aea9b694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;layout__Styles-sc-csgnm7-0 iJzkTS&quot;]/div[@class=&quot;quotation__Styles-sc-1i79f2c-0 izxPpS bg-white&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;first-form row&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;QuoteForm__Styles-sc-fhdaqy-0 eXPZRQ shadow p-3 rounded bg-body-tertiary&quot;]/form[1]/div[@class=&quot;justify-content-center gap-3 mb-4 row&quot;]/div[@class=&quot;negative-offset col-md-8&quot;]/div[1]/div[@class=&quot;input-group&quot;]/input[@class=&quot;TextInputV2__FormControl-sc-1yhoudg-0 fmqRdx undefined undefined form-control&quot;]</value>
      <webElementGuid>e5c47847-2108-4e6c-aa25-ab48aeead8cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='vehicleDetails.chassisNumber']</value>
      <webElementGuid>3c69a472-edbb-4ca6-93e1-858aade44d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/div[2]/div/div/div/form/div[7]/div/div/div/input</value>
      <webElementGuid>6db3de87-da12-4703-80d5-e05de2880107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/input</value>
      <webElementGuid>25f4b5a9-660a-4298-8533-fed1c6245464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Type in your car chassis number' and @name = 'vehicleDetails.chassisNumber' and @type = 'text']</value>
      <webElementGuid>986f65f7-40fc-44c8-b08a-c02b944c345d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
