<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_vehicleNumber</name>
   <tag></tag>
   <elementGuidId>eb9b5a2d-baea-45ac-aac8-f7f57414aa42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='vehicleDetails.vehicleNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;vehicleDetails.vehicleNumber&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;E.G. : NBT7889&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7a277e6-4743-40ca-9fad-0dfad38effad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>1707659a-5071-47c0-964b-3f88eaf75608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>E.G. : NBT7889</value>
      <webElementGuid>3346eff3-0dc2-46bc-ac1e-2176e2fad509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vehicleDetails.vehicleNumber</value>
      <webElementGuid>b3c63727-fbac-48b3-bcbc-a41b0651767e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dc7bfec2-53b5-45f8-9afe-ba183dd8d51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextInputV2__FormControl-sc-1yhoudg-0 iTxspb undefined undefined form-control</value>
      <webElementGuid>8b6c1240-3782-4a71-98ef-271525662a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;layout__Styles-sc-csgnm7-0 iJzkTS&quot;]/div[@class=&quot;quotation__Styles-sc-1i79f2c-0 izxPpS bg-white&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;first-form row&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;QuoteForm__Styles-sc-fhdaqy-0 eXPZRQ shadow p-3 rounded bg-body-tertiary&quot;]/form[1]/div[@class=&quot;justify-content-center gap-3 mb-4 row&quot;]/div[@class=&quot;col-md-4&quot;]/div[1]/div[@class=&quot;input-group&quot;]/input[@class=&quot;TextInputV2__FormControl-sc-1yhoudg-0 iTxspb undefined undefined form-control&quot;]</value>
      <webElementGuid>7896d827-1cea-4745-891d-b2903c23d36c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='vehicleDetails.vehicleNumber']</value>
      <webElementGuid>7ecf9b74-9bf9-4d4e-a10e-fba30f31f026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/div[2]/div/div/div/form/div[3]/div[3]/div/div/input</value>
      <webElementGuid>63de237b-614d-47f3-a6f5-3a9dd1f39a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>844156fe-5b5b-40d1-a43a-90d688e410df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'E.G. : NBT7889' and @name = 'vehicleDetails.vehicleNumber' and @type = 'text']</value>
      <webElementGuid>6d8e8d9d-a156-41ff-a27e-30b08f7c3a10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
