<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_AnnualTrip</name>
   <tag></tag>
   <elementGuidId>62b9b0ab-86be-47df-8210-d0bd656111f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tripType_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tripType_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b453ddb-d954-46cd-a066-51240a156023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tripType</value>
      <webElementGuid>674eb785-f13d-491b-b30a-94ddf407322d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>afc018b5-643d-4f91-ad40-a4ecba79908e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tripType_2</value>
      <webElementGuid>da98af23-8486-48d0-8aba-c59e1ad95ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>d76e280e-c051-46b9-a790-4fbc293bea25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>21974877-56dc-4d83-ae1c-ede40ece80ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tripType_2&quot;)</value>
      <webElementGuid>21b3a3fa-1136-4025-8ae7-e802fcb4b587</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tripType_2']</value>
      <webElementGuid>c34fa8bd-6dff-4281-b50a-a66e0cca7419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div/div[2]/div[2]/div/form/div/div[2]/input</value>
      <webElementGuid>c12052ee-a3d4-4e9d-bff4-e81af97ae93b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>478eb2dc-3aa5-4852-92dc-6505f192f996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'tripType' and @type = 'radio' and @id = 'tripType_2']</value>
      <webElementGuid>ec8b4d8d-df32-410d-984c-44f6face6d23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
