<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SingleTrip</name>
   <tag></tag>
   <elementGuidId>fea92ef5-a288-4c05-8ec7-2612ccb3ae96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tripType_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tripType_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>971c7726-1869-4b8c-b09b-72023b469caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tripType</value>
      <webElementGuid>ecb524c9-ee1d-43ac-bcb6-ebafa7b8fbf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>fe4bdd84-3748-4c05-af44-c850841e0059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tripType_1</value>
      <webElementGuid>1d2bd027-a755-4bba-ba64-ff4f242f6f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>deef5ec9-61ea-490a-9555-71f29de85111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>775b2451-8817-46ad-9835-71a11f769554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tripType_1&quot;)</value>
      <webElementGuid>6417c614-d835-4bb2-9ccd-e20c153d41a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tripType_1']</value>
      <webElementGuid>2b5b1694-3f33-4567-8728-4af13599f8a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div/div[2]/div[2]/div/form/div/div/input</value>
      <webElementGuid>2ee776fa-c89a-4280-831c-c37dddad5c31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4f6da3ae-974f-42ea-8aa4-edf69781bf0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'tripType' and @type = 'radio' and @id = 'tripType_1']</value>
      <webElementGuid>5238833e-2d38-47bb-8ab7-09679b549353</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
