<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_LanguageEN</name>
   <tag></tag>
   <elementGuidId>9f7d8993-359b-4381-8369-bfd43bbaa528</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div/div/div[2]/div/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.bi.bi-globe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>i >> internal:has-text=&quot;EN&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>6785ab5a-67b8-43d6-87d5-96f4c70236c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-globe</value>
      <webElementGuid>d3e3c2c0-727a-49f9-9ee8-5d2aeb006119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>button-tooltip</value>
      <webElementGuid>e7ee76f0-e54b-4655-bc0d-188b1ad5a676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EN</value>
      <webElementGuid>961b30fb-7f71-4db5-b54e-3b7a619d02e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;Layout__Styles-sc-d7vu2k-0 fGSPvF&quot;]/div[@class=&quot;ml-0 p-0 m-0 container-fluid&quot;]/div[@class=&quot;quotation__Styles-sc-1lv5yzf-1 jbYbpZ&quot;]/div[@class=&quot;main-page&quot;]/div[@class=&quot;quote-form-component&quot;]/div[@class=&quot;text-end mt-4 pt-2&quot;]/div[@class=&quot;LanguageSwitcher__Wrapper-sc-14n6m5u-0 gkjnlb&quot;]/i[@class=&quot;bi bi-globe&quot;]</value>
      <webElementGuid>9ca0679e-6ad0-4825-a89f-f2b6aa0dfd57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div/div/div[2]/div/div/i</value>
      <webElementGuid>ee6b90cf-1fcb-413d-8555-7b16939eae5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click here.'])[1]/following::i[1]</value>
      <webElementGuid>2fa9b5dc-ebd2-4dde-a83f-b0e64131d487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Single Trip'])[1]/preceding::i[1]</value>
      <webElementGuid>75397a65-a137-4280-acbe-a5d9f2ca8d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/i</value>
      <webElementGuid>aaedb98f-ce00-4173-9f58-3b9f09a8e933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'EN' or . = 'EN')]</value>
      <webElementGuid>605b4c0a-825d-474c-909e-9dea7aca8918</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
