<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dybutton_SelectPlanType_planType</name>
   <tag></tag>
   <elementGuidId>4a831efc-359e-4a04-842f-9cddf6a99dce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-item</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '#' and (text() = 'Just myself' or . = 'Just myself')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='planType']//following-sibling::div//a[contains(text(), '${planType}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2a1fdb3e-cc41-4629-9a7f-f53541491cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b0155396-994d-442d-85d3-99321c56f9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>12fccea1-fd11-4916-8677-94afa71ddb35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b8d81b58-94e7-4dff-9d64-faab050294e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cb28241f-7941-43cc-942e-15aea48c6683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>6e0c5eb0-a87b-41a6-9385-6d38d739b188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Just myself</value>
      <webElementGuid>a067e11a-a9c5-4603-a2b3-f6d8e3be01d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;Layout__Styles-sc-d7vu2k-0 fGSPvF&quot;]/div[@class=&quot;quotation__Styles-sc-1ea5jab-0 pofmb&quot;]/div[@class=&quot;main-page&quot;]/div[@class=&quot;quote-form-component&quot;]/div[@class=&quot;QuoteForm__Styles-sc-8eq6jo-6 cuPXsd&quot;]/div[@class=&quot;quote-form&quot;]/form[1]/div[@class=&quot;QuoteForm__FormGroupWrapper-sc-8eq6jo-1 klvkIb&quot;]/div[@class=&quot;QuoteForm__FormGroup-sc-8eq6jo-2 kEyEqe mb-0 border-bottom-0&quot;]/div[@class=&quot;show dropdown&quot;]/div[@class=&quot;dropdown-menu-travelling-with dropdown-menu show&quot;]/div[@class=&quot;dropdown-item-div-travelling-with&quot;]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>a08f7f38-7c4b-4bf1-8f0f-0085e1978c18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div/div/div[2]/div[3]/div/form/div[3]/div[3]/div/div/div/div/a</value>
      <webElementGuid>f3ef9be7-3ff0-432d-806d-a630e8a34bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Just myself')]</value>
      <webElementGuid>012e04b9-6668-4522-ba65-65373a125c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select...'])[1]/following::a[1]</value>
      <webElementGuid>19b53384-924c-48bf-aa0c-33bba8e5e0a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Who are you travelling with?'])[1]/following::a[1]</value>
      <webElementGuid>dc8c1671-a293-4368-9c29-dadc8b119d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Age above 70)'])[1]/preceding::a[1]</value>
      <webElementGuid>5f61df0d-aaf7-4082-b541-2a27d2ab3a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Quote Now'])[1]/preceding::a[4]</value>
      <webElementGuid>60636209-ccdd-4797-a1ed-03711b304c25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Just myself']/parent::*</value>
      <webElementGuid>e9487be6-4281-4b20-8ceb-d5f45a912e3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>beef29a3-9e76-4f7e-95b4-1c04cbc774d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/a</value>
      <webElementGuid>1299f5ce-9492-4856-b5bc-23652d741f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Just myself(18 - 70 years old)' or . = 'Just myself(18 - 70 years old)')]</value>
      <webElementGuid>7225dbb2-7aa9-4574-ae8f-5df51051a46c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
