<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Clickhere</name>
   <tag></tag>
   <elementGuidId>acaf55ee-61ae-49d2-b7fa-e240d35593bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='clickMoreDetails']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#clickMoreDetails</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Click here.&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>045483a6-02ef-4bfe-a83c-0853a2c0cae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>393c7db5-562b-4774-b56b-746a830065d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.etiqa.com.my/v2/travel-insurance-takaful/tripcare-360-insurance?_ga=2.122784267.1409625373.1732675828-285224350.1732675828</value>
      <webElementGuid>20f1e950-09fe-4980-802e-1d489e92b7d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-link</value>
      <webElementGuid>d48b44e7-87d3-459c-b536-3190a69ebd0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clickMoreDetails</value>
      <webElementGuid>44604896-d972-40cc-b7e8-e66d6beb0536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noreferrer</value>
      <webElementGuid>c4c92483-0da3-48b7-84f8-72e0b14cad7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click here.</value>
      <webElementGuid>e48f6cd6-8020-4890-bd5c-b66943b24c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clickMoreDetails&quot;)</value>
      <webElementGuid>cfc01162-b2cc-433d-9bd0-51feeb890a05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='clickMoreDetails']</value>
      <webElementGuid>645facae-af86-4175-8924-da5ebd892ba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div/div/div/div/div/div/div/div/div/div[8]/a</value>
      <webElementGuid>8440007e-9b5d-4c1e-8af5-6e5a408ce491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Click here.')]</value>
      <webElementGuid>2672d606-b689-4a8a-a333-213a692c1879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add-on options for adventurous activities'])[1]/following::a[1]</value>
      <webElementGuid>b8545eb6-130d-4bca-b4ae-3ed473a94de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[1]/preceding::a[1]</value>
      <webElementGuid>2c0fb66a-88da-4b8f-87a9-52191f1383d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Single Trip'])[1]/preceding::a[1]</value>
      <webElementGuid>96bd6d43-93ea-49fd-8448-8bccd839a9a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Click here.']/parent::*</value>
      <webElementGuid>9baa47fb-e219-4474-9d3c-9b4f5ae6169c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.etiqa.com.my/v2/travel-insurance-takaful/tripcare-360-insurance?_ga=2.122784267.1409625373.1732675828-285224350.1732675828')]</value>
      <webElementGuid>ab360f8f-779c-4bac-9274-778cef6b2786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>6d2cc8dd-1aca-4832-8eca-c4a2ed06ebea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.etiqa.com.my/v2/travel-insurance-takaful/tripcare-360-insurance?_ga=2.122784267.1409625373.1732675828-285224350.1732675828' and @id = 'clickMoreDetails' and (text() = 'Click here.' or . = 'Click here.')]</value>
      <webElementGuid>abf9dfd0-420d-4cef-8f01-8b6be236c665</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
