<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save Bank Details</name>
   <tag></tag>
   <elementGuidId>583c60d2-364f-41f0-9476-8490dfcad93e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[contains(@class,'BankAccountDetailsForm__Buttons-sc-1n6vmoa-1')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>fc731a5f-7f83-4c1d-b05d-df77a33ac8de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1735550770827</value>
      <webElementGuid>3764ac03-c4f4-42b0-803b-856ea3544c59</webElementGuid>
   </webElementProperties>
</WebElementEntity>
