<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close Bank Details</name>
   <tag></tag>
   <elementGuidId>c745a58f-fd4d-4b9c-960d-a17be40a18b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[contains(@class,'BankAccountDetailsForm__Buttons-sc-1n6vmoa-1')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>c8eb5911-2622-4ad9-be99-dd9659463380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1735550793117</value>
      <webElementGuid>2134f03d-dd48-455d-ba0f-ef76580cf214</webElementGuid>
   </webElementProperties>
</WebElementEntity>
