<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wrnmsg_Account Number</name>
   <tag></tag>
   <elementGuidId>5ecd6066-ff32-4f2e-a6e1-b30fcb6c2e9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='accountNo']/following-sibling::p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>2768aca6-0883-4f9c-8625-5cf4a24ee5d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1735869578013</value>
      <webElementGuid>fd761bea-9efd-4564-9d2b-13e3c44797da</webElementGuid>
   </webElementProperties>
</WebElementEntity>
