<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_diningRoomAmount</name>
   <tag></tag>
   <elementGuidId>5516636a-9740-4314-8710-0f932279d991</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='diningRoomAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;diningRoomAmount&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;diningRoomAmount&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>434fa98e-7587-406d-b6e9-581ece085d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>5a568878-3cd0-43a4-86c4-6c05b7b8b7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>diningRoomAmount</value>
      <webElementGuid>53bee7c8-3de2-4b82-bd09-d5ba4d69bfc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1579df7f-a277-4687-a6d9-db721ff40a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AmountInput__FormControl-sc-xyqav3-0 iFmBta form-control</value>
      <webElementGuid>2109b575-53f4-4825-9186-1619ca48fecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;layout__Styles-sc-wetbic-0 ehlvJr&quot;]/div[@class=&quot;plan__Styles-sc-1bba8d0-0 dlSxDC bg-white&quot;]/div[@class=&quot;ContentCalculator__Styles-sc-srpzpt-0 kXGYRB&quot;]/div[@class=&quot;container-padding-hide container&quot;]/div[@class=&quot;mb-5&quot;]/div[3]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;my-2 custom card&quot;]/div[@class=&quot;content-card card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;false col-md-4&quot;]/div[@class=&quot;AmountInput__FormGroup-sc-xyqav3-1 fzkICv&quot;]/div[@class=&quot;undefined undefined input-group&quot;]/input[@class=&quot;AmountInput__FormControl-sc-xyqav3-0 iFmBta form-control&quot;]</value>
      <webElementGuid>3e02c26c-2344-4139-aced-26063812623d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='diningRoomAmount']</value>
      <webElementGuid>a9f71b45-1650-4ba2-b07d-6ecd271e855c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/div/div/div/div[3]/div/div[3]/div/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>e75fe684-59e3-47fe-8a15-d69823e16102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>7e9b3686-8494-4acf-9a4c-2770075e2826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'diningRoomAmount' and @type = 'text']</value>
      <webElementGuid>ee679478-e96e-4226-bda9-3496aae9c9a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
