<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_livingRoomAmount</name>
   <tag></tag>
   <elementGuidId>c09780d0-728d-4b4d-942c-ab891290e068</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='livingRoomAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;livingRoomAmount&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;livingRoomAmount&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0afecd88-6b27-4371-9d81-439a9236c102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>c2da724d-de12-4773-bd73-0eb3257df8fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>livingRoomAmount</value>
      <webElementGuid>d69e9c32-bebd-4f55-8ad2-6ec3c8bc1420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6d40d71b-f639-4693-9cb4-538bace8b437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AmountInput__FormControl-sc-xyqav3-0 iFmBta form-control</value>
      <webElementGuid>b3537424-038b-4f87-8314-b495c39faf5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;layout__Styles-sc-wetbic-0 ehlvJr&quot;]/div[@class=&quot;plan__Styles-sc-1bba8d0-0 dlSxDC bg-white&quot;]/div[@class=&quot;ContentCalculator__Styles-sc-srpzpt-0 kXGYRB&quot;]/div[@class=&quot;container-padding-hide container&quot;]/div[@class=&quot;mb-5&quot;]/div[3]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;my-2 custom card&quot;]/div[@class=&quot;content-card card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;false col-md-4&quot;]/div[@class=&quot;AmountInput__FormGroup-sc-xyqav3-1 fzkICv&quot;]/div[@class=&quot;undefined undefined input-group&quot;]/input[@class=&quot;AmountInput__FormControl-sc-xyqav3-0 iFmBta form-control&quot;]</value>
      <webElementGuid>82ea1ba6-ba7b-42eb-9d58-10857530056e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='livingRoomAmount']</value>
      <webElementGuid>82c7ddaa-581e-4608-a3be-dd40beb806e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/div/div/div/div[3]/div/div/div/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>5864442d-a1cd-4c22-9abc-ff6ab613b594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>54df5032-8b13-42fc-8b24-5fb285e66526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'livingRoomAmount' and @type = 'text']</value>
      <webElementGuid>ee571bcb-b0ce-4e7d-90dc-ee180cbbd046</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
