<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_gardenAmount</name>
   <tag></tag>
   <elementGuidId>d695aac4-b8e3-42af-93c9-70a0bf23ccb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='gardenAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;gardenAmount&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;gardenAmount&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f6a885d-f002-4eb5-bf92-7555c6655a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>9149b797-956b-40ef-9cc9-b82b4c0263ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gardenAmount</value>
      <webElementGuid>4576f48d-b8b0-4e0e-b21b-23d658bd47ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a764bf57-0c7f-4a83-acf4-40ef0c6f754c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AmountInput__FormControl-sc-xyqav3-0 iFmBta form-control</value>
      <webElementGuid>ddbc4aef-c173-42db-99fe-b09d962a7c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;layout__Styles-sc-wetbic-0 ehlvJr&quot;]/div[@class=&quot;plan__Styles-sc-1bba8d0-0 dlSxDC bg-white&quot;]/div[@class=&quot;ContentCalculator__Styles-sc-srpzpt-0 kXGYRB&quot;]/div[@class=&quot;container-padding-hide container&quot;]/div[@class=&quot;mb-5&quot;]/div[3]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;my-2 custom card&quot;]/div[@class=&quot;content-card card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;false col-md-6&quot;]/div[@class=&quot;AmountInput__FormGroup-sc-xyqav3-1 fzkICv&quot;]/div[@class=&quot;undefined undefined input-group&quot;]/input[@class=&quot;AmountInput__FormControl-sc-xyqav3-0 iFmBta form-control&quot;]</value>
      <webElementGuid>49dc7076-ee03-4b53-833c-2d5a16eb89b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='gardenAmount']</value>
      <webElementGuid>f8a85e5c-214f-4f44-af1a-5f042903466a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/div/div/div/div[3]/div/div[9]/div/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>be333094-9ef0-4622-b45b-e238d7bb6e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>27dddcdb-00a3-49ad-948e-e47341c92a76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'gardenAmount' and @type = 'text']</value>
      <webElementGuid>6c6eef42-67a9-40ef-9ad0-1068a5bb2491</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
