<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_kitchenAmount</name>
   <tag></tag>
   <elementGuidId>2aab9c83-f4d7-4715-a069-3c555e725ef1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='kitchenAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;kitchenAmount&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;kitchenAmount&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73980476-3e22-4afd-8ebb-96e032ab0e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>a27012bf-b2f7-4bfe-8fe2-f6e5d71329f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kitchenAmount</value>
      <webElementGuid>735c234c-4d0d-43c8-b53e-9ca12d57b0b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>88d0075f-c792-44b9-9869-142f07b59bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AmountInput__FormControl-sc-xyqav3-0 iFmBta form-control</value>
      <webElementGuid>837d6ff3-681b-4b3f-a35a-7dc1d1a1a87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;layout__Styles-sc-wetbic-0 ehlvJr&quot;]/div[@class=&quot;plan__Styles-sc-1bba8d0-0 dlSxDC bg-white&quot;]/div[@class=&quot;ContentCalculator__Styles-sc-srpzpt-0 kXGYRB&quot;]/div[@class=&quot;container-padding-hide container&quot;]/div[@class=&quot;mb-5&quot;]/div[3]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;my-2 custom card&quot;]/div[@class=&quot;content-card card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;false col-md-4&quot;]/div[@class=&quot;AmountInput__FormGroup-sc-xyqav3-1 fzkICv&quot;]/div[@class=&quot;undefined undefined input-group&quot;]/input[@class=&quot;AmountInput__FormControl-sc-xyqav3-0 iFmBta form-control&quot;]</value>
      <webElementGuid>f474039c-a494-40e8-90d8-a4d9d430edc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='kitchenAmount']</value>
      <webElementGuid>e1c61555-1e18-4061-91c1-a7ad4a727261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/div/div/div/div[3]/div/div[4]/div/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>919d8492-9e57-4e74-867b-6d3432d98552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>b602a128-03c8-40ac-8741-95c43791ef40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'kitchenAmount' and @type = 'text']</value>
      <webElementGuid>822d27e6-983c-4dc6-bc85-0595a76f31f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
