<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_FlightDate1</name>
   <tag></tag>
   <elementGuidId>ea86676e-53ec-44fa-bb66-48467b9a39d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;day&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='day']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d18161ee-a857-49cb-b0c5-679a73313dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>day</value>
      <webElementGuid>d0db264a-50db-47a3-9c3f-c0e482bfaa51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rdp-button_reset rdp-button rdp-day rdp-day_disabled</value>
      <webElementGuid>f5916b05-75f5-4198-95c6-f23fe4265a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>bdf2b50f-81ed-4d99-8cda-96cc4fbc3db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b16ba5ad-d311-4075-8096-9b942abd252f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c4bfd112-6334-498e-943e-de5a8476bcc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9165c136-ea63-45dc-8fdb-f786beea7d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;Layout__Styles-sc-d7vu2k-0 fGSPvF&quot;]/div[@class=&quot;mt-3 container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-7 col-12&quot;]/form[1]/div[1]/div[@class=&quot;mt-5&quot;]/div[@class=&quot;FlightDetailForm__Styles-sc-zquz6k-1 fysaWR&quot;]/div[@class=&quot;shadow mb-3  card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;mb-3&quot;]/div[@class=&quot;SingleDatePicker__Styles-sc-1nrwzub-0 gBJcxo&quot;]/div[@class=&quot;day-picker-display-top&quot;]/div[@class=&quot;rdp&quot;]/div[@class=&quot;rdp-months&quot;]/div[@class=&quot;rdp-month rdp-caption_start rdp-caption_end&quot;]/table[@class=&quot;rdp-table&quot;]/tbody[@class=&quot;rdp-tbody&quot;]/tr[@class=&quot;rdp-row&quot;]/td[@class=&quot;rdp-cell&quot;]/button[@class=&quot;rdp-button_reset rdp-button rdp-day rdp-day_disabled&quot;]</value>
      <webElementGuid>e118185b-f984-414a-bf05-91915524889f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='day']</value>
      <webElementGuid>7a4cb411-aeb1-46e6-8d6d-a2587b7c52a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div[2]/div/form/div/div/div[2]/div/div/div[3]/div/div/div/div/div/table/tbody/tr/td[6]/button</value>
      <webElementGuid>110105dd-8ee2-4a4f-bfda-efad4a393738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::button[1]</value>
      <webElementGuid>a64c47ad-ca31-4d4a-a0a2-b22de870bdaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::button[1]</value>
      <webElementGuid>fe62976e-aaa3-4e11-9690-829b1768330f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Policy Holder Name'])[1]/preceding::button[31]</value>
      <webElementGuid>99bbf6b8-de4e-4ebf-b9a2-994ac85514e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Name'])[1]/preceding::button[31]</value>
      <webElementGuid>5b1d106a-c361-4cd7-84fb-0378e13b5324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1']/parent::*</value>
      <webElementGuid>880253bd-dc6f-408b-bb41-dcf98538b86f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/button</value>
      <webElementGuid>2cec6694-9f6e-41de-808a-77536ed36277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'day' and @type = 'button' and (text() = '1' or . = '1')]</value>
      <webElementGuid>d0a88547-74c0-4223-9602-8b735ef24a8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
