<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_FlightDate2</name>
   <tag></tag>
   <elementGuidId>07759cf6-bce6-45c2-aef4-78c7d9c5ba31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@name='day'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a470cd51-5a95-4b55-b6fc-d8ab7da0031e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>day</value>
      <webElementGuid>0d234260-1ba8-4427-bc12-2a7da48b8d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rdp-button_reset rdp-button rdp-day rdp-day_selected</value>
      <webElementGuid>e3936bc1-fed3-4fdf-82ab-ced6597d70b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>5ba09a04-dca2-4cea-ba21-0d25b49ceb71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>40f06db3-f1ab-49b9-883f-622ce4138b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c3dfeb2e-c1e7-40bf-bab4-72b3913702fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>57e8afec-dca1-4dab-886a-d6fe0f2cd022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>72447471-206a-4209-ab56-77caffa1439e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;Layout__Styles-sc-d7vu2k-0 fGSPvF&quot;]/div[@class=&quot;mt-3 container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-7 col-12&quot;]/form[1]/div[1]/div[@class=&quot;mt-5&quot;]/div[@class=&quot;FlightDetailForm__Styles-sc-zquz6k-1 fysaWR&quot;]/div[@class=&quot;shadow mb-3  card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;mb-3&quot;]/div[@class=&quot;SingleDatePicker__Styles-sc-1nrwzub-0 gBJcxo&quot;]/div[@class=&quot;day-picker-display-top&quot;]/div[@class=&quot;rdp&quot;]/div[@class=&quot;rdp-months&quot;]/div[@class=&quot;rdp-month rdp-caption_start rdp-caption_end&quot;]/table[@class=&quot;rdp-table&quot;]/tbody[@class=&quot;rdp-tbody&quot;]/tr[@class=&quot;rdp-row&quot;]/td[@class=&quot;rdp-cell&quot;]/button[@class=&quot;rdp-button_reset rdp-button rdp-day rdp-day_selected&quot;]</value>
      <webElementGuid>a99a1030-59ac-4220-81aa-f672b4bb6fa9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@name='day'])[2]</value>
      <webElementGuid>b4df9e4e-0ddb-4448-b0c3-1483d28de490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div[2]/div/form/div/div/div/div/div/div[3]/div/div/div/div/div/table/tbody/tr/td[7]/button</value>
      <webElementGuid>2f923714-d159-4e92-a1ae-f00e99a622c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::button[2]</value>
      <webElementGuid>7a378e30-245c-4e32-a22f-779b2be18d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::button[2]</value>
      <webElementGuid>a390a356-e4f6-4533-886e-7758e9027372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return Flight'])[1]/preceding::button[30]</value>
      <webElementGuid>8081ff40-33d4-40aa-86e6-55b73819ff64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flight Number'])[2]/preceding::button[30]</value>
      <webElementGuid>ec8efbf5-38e9-41e2-b5bc-0a83da94ebed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2']/parent::*</value>
      <webElementGuid>8c7cb977-1f54-4ea5-ade6-c88fbc7fe8d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/button</value>
      <webElementGuid>40d97fc8-c98f-4927-a2c3-ffdd8dc907ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'day' and @type = 'button' and (text() = '2' or . = '2')]</value>
      <webElementGuid>acaf018e-b5a7-4c0e-ae2a-1af8d19801c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
