<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dybutton_Date_date</name>
   <tag></tag>
   <elementGuidId>c86eec58-1877-4a4f-85ca-ef5eca4b2c04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;day&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='day' and text() = '${date}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>54f14f8a-4405-4c61-817d-9ab19cd4efba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>day</value>
      <webElementGuid>55b6aaa0-cc5d-44c2-96a2-e9d3e198c522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rdp-button_reset rdp-button rdp-day</value>
      <webElementGuid>05de9ede-334b-4340-90af-7eac3d1642e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>b24e28dd-b840-432c-b5b6-ce2cc8105a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8be94cd0-5350-4e1f-8def-c23b412ae8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>860a1e18-8cb3-41e3-9700-1c177faf47a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7916c34d-e247-4ca7-aba1-e8418f75453f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;Layout__Styles-sc-d7vu2k-0 fGSPvF&quot;]/div[@class=&quot;quotation__Styles-sc-1ea5jab-0 pofmb&quot;]/div[@class=&quot;main-page&quot;]/div[@class=&quot;quote-form-component&quot;]/div[@class=&quot;QuoteForm__Styles-sc-8eq6jo-6 cuPXsd&quot;]/div[@class=&quot;quote-form&quot;]/form[1]/div[@class=&quot;QuoteForm__FormGroupWrapper-sc-8eq6jo-1 klvkIb&quot;]/div[@class=&quot;QuoteForm__FormGroup-sc-8eq6jo-2 kEyEqe&quot;]/div[@class=&quot;DayRangePicker__Styles-sc-noptr6-0 KhFML&quot;]/div[@class=&quot;day-picker&quot;]/div[@class=&quot;day-picker-display-top&quot;]/div[@class=&quot;rdp&quot;]/div[@class=&quot;rdp-months&quot;]/div[@class=&quot;rdp-month rdp-caption_start rdp-caption_end&quot;]/table[@class=&quot;rdp-table&quot;]/tbody[@class=&quot;rdp-tbody&quot;]/tr[@class=&quot;rdp-row&quot;]/td[@class=&quot;rdp-cell&quot;]/button[@class=&quot;rdp-button_reset rdp-button rdp-day&quot;]</value>
      <webElementGuid>1178d665-512e-481d-8fab-55ff3ca8b088</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='day']</value>
      <webElementGuid>0f9d348e-88cd-4b71-a3d0-e948ed68c292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div/div[2]/div[2]/div/form/div[2]/div[2]/div/div/div[3]/div/div/div/table/tbody/tr/td[6]/button</value>
      <webElementGuid>3182ca7f-0376-424b-9a7b-6023b077623e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::button[1]</value>
      <webElementGuid>a619653b-3f1c-41f2-a5c7-79c66a93b5e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::button[1]</value>
      <webElementGuid>307a7024-5853-4f99-82ec-cf22c3f3d63f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Who are you travelling with?'])[1]/preceding::button[31]</value>
      <webElementGuid>c498b89e-beee-4232-9f44-6c4fa865a3e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select...'])[1]/preceding::button[31]</value>
      <webElementGuid>3fcaed77-efb8-407f-96e0-f531c39fc87b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1']/parent::*</value>
      <webElementGuid>7c717187-fb7a-4d4e-8b78-6ac936dc363e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/button</value>
      <webElementGuid>50db888c-50b3-4e3d-aa04-de05f3b34a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'day' and @type = 'button' and (text() = '1' or . = '1')]</value>
      <webElementGuid>f700f80c-a518-48c8-964b-2214297d2739</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
