<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_MarketingConsent</name>
   <tag></tag>
   <elementGuidId>53dcd8be-6448-4c27-bab3-24b7e92b3540</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='marketingConsent']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#marketingConsent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed460832-edb8-43c3-a37f-84611da909aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>marketingConsent</value>
      <webElementGuid>01845fea-d4d1-4468-9f70-b471d248a451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2b9d593d-1def-4c6d-9eb1-4136a935db1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>marketingConsent</value>
      <webElementGuid>68734c53-6f0b-4a5d-96b1-8a99352fd8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>87962dc0-0413-44fe-8606-cfe67b543db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;marketingConsent&quot;)</value>
      <webElementGuid>3730f713-30e5-418b-9f0b-25561565b287</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='marketingConsent']</value>
      <webElementGuid>3b098e03-b273-434f-8c5c-82bf3a5e6949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div/form/div/div/div[4]/div[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>ba19ecd6-58ee-4b83-b9f1-9d849b8e914f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>471c6b00-852c-4f77-a867-63f066a73ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'marketingConsent' and @type = 'checkbox' and @id = 'marketingConsent']</value>
      <webElementGuid>3bc7e85f-a8de-455a-ae0c-e2939d039f1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
