<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dysubmit_ProceedPayment_button</name>
   <tag></tag>
   <elementGuidId>b76f0e9f-0792-423a-b343-78dc683b7ed7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(text(), '${button}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.px-4.py-2.float-end.btn.btn-warning.btn-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8da0ece5-43ac-41b9-b00c-e79b3c05e92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b8af85ce-d45c-4e6a-a140-460f458649c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 py-2 float-end btn btn-warning btn-sm</value>
      <webElementGuid>093a8385-c5b9-48ed-b85a-838e39843cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proceed Payment</value>
      <webElementGuid>1c7a4116-266d-4b8d-8e40-4478f839c083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;Layout__Styles-sc-d7vu2k-0 fGSPvF&quot;]/div[@class=&quot;review__Styles-sc-1y5xbh0-1 jrSuyi&quot;]/div[@class=&quot;mt-3 container&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-7 col-12&quot;]/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;mt-4 row&quot;]/div[@class=&quot;p-0&quot;]/button[@class=&quot;px-4 py-2 float-end btn btn-warning btn-sm&quot;]</value>
      <webElementGuid>7345a968-e283-4cc6-94f6-772e7b2da85f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[7]</value>
      <webElementGuid>d9d0e153-68dc-4313-9e17-f64ba402c87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div/form/div[2]/div/div/div/div/div/button[2]</value>
      <webElementGuid>bd0606a9-0dcc-4dfe-b12c-d64dedda7fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::button[1]</value>
      <webElementGuid>4c20d49c-0359-4283-bf1f-386861e89b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RM222.99'])[1]/following::button[2]</value>
      <webElementGuid>4d4b7ee8-6446-4308-898a-02475c984d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Navigated to Quotation | TripCare 360'])[1]/preceding::button[1]</value>
      <webElementGuid>f187be9b-d297-489f-b397-efb8f07d483d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[1]</value>
      <webElementGuid>a0ba6fc6-2836-43cb-a5bd-9d433e28f588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Proceed Payment']/parent::*</value>
      <webElementGuid>efc66055-ac58-4fd5-b098-b1913546f73d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>747118e3-70e0-4401-b036-d5681d924406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Proceed Payment' or . = 'Proceed Payment')]</value>
      <webElementGuid>b3ebd379-6ed2-4d96-a279-2a5214d1bf94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
