<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_etiqaLogo</name>
   <tag></tag>
   <elementGuidId>be020585-e1b3-44e2-8585-cf0a6d8a2870</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@alt = 'etiqa' and @src = '/tripcare360/static/Etiqa_logos_Full Colour-d94497bbf6244e4ea4ce9562c78d8663.png']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.etiqa-logo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b3af91b2-2f99-4b24-a91f-54e515d692a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>etiqa</value>
      <webElementGuid>9c4d845f-dbaf-4838-a950-4c063634f653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/tripcare360/static/Etiqa_logos_Full Colour-d94497bbf6244e4ea4ce9562c78d8663.png</value>
      <webElementGuid>9107612c-7756-4440-bdbd-9063fb0e877d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>etiqa-logo</value>
      <webElementGuid>6eba3906-09b9-46e6-8a15-caf69605814c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;Layout__Styles-sc-d7vu2k-0 fGSPvF&quot;]/div[@class=&quot;amla__Styles-sc-1e8lq61-0 gvSioT&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/img[@class=&quot;etiqa-logo&quot;]</value>
      <webElementGuid>3a5c17e8-b117-45e2-81f5-e9c91cd90df7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div/div/div/img</value>
      <webElementGuid>330b472a-73cb-4725-a192-f1c95bbed9f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='etiqa']</value>
      <webElementGuid>a3bf217d-4d4e-461c-aa9e-c37313a79399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/img</value>
      <webElementGuid>ba687e3d-cda4-4d0b-9044-4d49baa8d14f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'etiqa' and @src = '/tripcare360/static/Etiqa_logos_Full Colour-d94497bbf6244e4ea4ce9562c78d8663.png']</value>
      <webElementGuid>90a45a9f-1314-4e17-8eb0-f338f72db6a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
