<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_etiqaLogo</name>
   <tag></tag>
   <elementGuidId>be020585-e1b3-44e2-8585-cf0a6d8a2870</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.etiqa-logo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2949e5af-ac3a-49c0-ad74-81689fc42f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>etiqa</value>
      <webElementGuid>6a197973-7402-400c-a80a-998edba6caa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/tripcare360/static/Etiqa_logos_Full Colour-d94497bbf6244e4ea4ce9562c78d8663.png</value>
      <webElementGuid>1eb1c98b-361b-44d7-99ed-04e71ccc6826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>etiqa-logo</value>
      <webElementGuid>7ddc82e8-87e6-4e8d-93c0-3345edb1f553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;Layout__Styles-sc-d7vu2k-0 fGSPvF&quot;]/div[@class=&quot;amla__Styles-sc-1e8lq61-0 gvSioT&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/img[@class=&quot;etiqa-logo&quot;]</value>
      <webElementGuid>8a3ac56b-4083-43a2-95e0-aab312792804</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div/div/div/img</value>
      <webElementGuid>af02b7cc-d34c-4229-a99a-2233e9087a8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='etiqa']</value>
      <webElementGuid>bc107eda-34e6-4f19-a81f-fb9719726818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/img</value>
      <webElementGuid>5f81f79e-0fbb-4262-9b1c-d40f86903680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'etiqa' and @src = '/tripcare360/static/Etiqa_logos_Full Colour-d94497bbf6244e4ea4ce9562c78d8663.png']</value>
      <webElementGuid>326dfe49-0822-42d5-b861-134d30bf6ff4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
