<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_ImportantNotice</name>
   <tag></tag>
   <elementGuidId>f8056a03-44e4-4bf4-a2e2-5f03e9ce8071</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@aria-label='important-notice']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>77f4245b-17ad-4235-9555-891f0c4c502f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-link</value>
      <webElementGuid>8c8b0274-af3f-4a36-8572-88b578d96d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tripcare360/static/ImportantNotice_Eng_Ins-ac0fd20ec2e0ee8bcba92c6874792163.pdf</value>
      <webElementGuid>6340d03e-0daf-4ea2-93e5-444a5d74cb02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>81eb0088-68f1-49a8-a33e-4723db4b3498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>important-notice</value>
      <webElementGuid>fecd918d-a862-4a76-8d63-edede4101880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noreferrer</value>
      <webElementGuid>b22cc933-3d0f-443b-b0a3-b6026fb60964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Important Notice</value>
      <webElementGuid>40449432-db38-405d-84af-d2915bc973f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;Layout__Styles-sc-d7vu2k-0 fGSPvF&quot;]/div[@class=&quot;review__Styles-sc-1y5xbh0-1 jrSuyi&quot;]/div[@class=&quot;mt-3 container&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-7 col-12&quot;]/div[@class=&quot;DeclarationForm__DeclarationDiv-sc-4vr836-4 hXczvA&quot;]/div[@class=&quot;box-container p-2 card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;DeclarationForm__Styles-sc-4vr836-0 jaeJwV&quot;]/div[@class=&quot;card.text&quot;]/div[1]/div[@class=&quot;d-flex gap-3&quot;]/div[2]/a[@class=&quot;a-link&quot;]</value>
      <webElementGuid>2f14af72-d30f-42d1-8030-75c0f1ab2b56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div/form/div/div/div[4]/div[2]/div/div/div/div/div[2]/div[2]/a[3]</value>
      <webElementGuid>e2d6846a-880a-45cb-b66f-1c25bed91ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Important Notice')]</value>
      <webElementGuid>ef38ff6e-ef01-43c0-b5a5-acc2f1209b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Policy Contract'])[1]/following::a[1]</value>
      <webElementGuid>2fb00d4d-f97b-4486-a31e-abe5be7fd431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Disclosure Sheet'])[1]/following::a[2]</value>
      <webElementGuid>4b58a0aa-2ef5-40de-83a1-89c819d5d448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Declaration'])[1]/preceding::a[1]</value>
      <webElementGuid>5840f10f-158a-447f-aa85-b26b9f320d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PIDM’s TIPS Brochure'])[1]/preceding::a[2]</value>
      <webElementGuid>6b97162e-8021-4893-9940-97ce42f0b62f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Important Notice']/parent::*</value>
      <webElementGuid>3b85bf96-26d8-4457-bc7b-797eac210509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/tripcare360/static/ImportantNotice_Eng_Ins-ac0fd20ec2e0ee8bcba92c6874792163.pdf')]</value>
      <webElementGuid>cbde27d6-4aea-468f-8c8d-6e563e1a66a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>7abe3bb5-5e4d-4542-9272-cfdccad26a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/tripcare360/static/ImportantNotice_Eng_Ins-ac0fd20ec2e0ee8bcba92c6874792163.pdf' and (text() = 'Important Notice' or . = 'Important Notice')]</value>
      <webElementGuid>492e170f-a6e8-4018-bbb5-5ff1b2f85df6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
