<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_PolicyContract</name>
   <tag></tag>
   <elementGuidId>5a79bdcb-ca5b-4a39-b3c9-96fb5fbd3146</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@aria-label='policy-contract']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b1f9ccbd-ad46-479c-a6f2-26fbe9e848a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-link</value>
      <webElementGuid>e4d04dc6-781f-40a2-a591-e634c82b86b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tripcare360/static/PolicyContract_Eng_Ins-9f433f20f1b4a4dfc0517b9d4bb3f8ed.pdf</value>
      <webElementGuid>a82a9525-50da-4999-a168-d88dc7e39b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>9dc8a851-76fc-4778-bfd2-dbbdc844f8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>policy-contract</value>
      <webElementGuid>fab677b9-6a94-4b02-95a9-52785ce8d40c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noreferrer</value>
      <webElementGuid>f277a2c4-0d42-4bf7-81e8-765712f4eb14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Policy Contract</value>
      <webElementGuid>5852a51f-da97-40c9-880c-954b24865d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;Layout__Styles-sc-d7vu2k-0 fGSPvF&quot;]/div[@class=&quot;review__Styles-sc-1y5xbh0-1 jrSuyi&quot;]/div[@class=&quot;mt-3 container&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-7 col-12&quot;]/div[@class=&quot;DeclarationForm__DeclarationDiv-sc-4vr836-4 hXczvA&quot;]/div[@class=&quot;box-container p-2 card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;DeclarationForm__Styles-sc-4vr836-0 jaeJwV&quot;]/div[@class=&quot;card.text&quot;]/div[1]/div[@class=&quot;d-flex gap-3&quot;]/div[2]/a[@class=&quot;a-link&quot;]</value>
      <webElementGuid>528045a4-3f85-4e32-9a94-061acb89e56c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div/form/div/div/div[4]/div[2]/div/div/div/div/div[2]/div[2]/a[2]</value>
      <webElementGuid>b693737e-e572-463b-a666-08100fa58117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Policy Contract')]</value>
      <webElementGuid>86618073-bba5-464f-9535-18bf9bd0cbbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Disclosure Sheet'])[1]/following::a[1]</value>
      <webElementGuid>090c5821-991e-4fe4-a301-c6114a75e0ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I confirm that I have read and agree to the'])[1]/following::a[2]</value>
      <webElementGuid>d91eb2e4-d8d3-4079-800e-d8b8e55768a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Important Notice'])[1]/preceding::a[1]</value>
      <webElementGuid>2ff6c124-5e85-463f-aa5e-92786de57216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Declaration'])[1]/preceding::a[2]</value>
      <webElementGuid>424bd843-1e53-4c5e-821f-cb7f9b7a656d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Policy Contract']/parent::*</value>
      <webElementGuid>c13b21aa-d5b5-45cb-b87d-b4cfec9a61f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/tripcare360/static/PolicyContract_Eng_Ins-9f433f20f1b4a4dfc0517b9d4bb3f8ed.pdf')]</value>
      <webElementGuid>bceae5a3-69d3-4c0c-8da7-93b30cdd63a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>8237d9f5-2954-46be-8c4e-8db058bf6a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/tripcare360/static/PolicyContract_Eng_Ins-9f433f20f1b4a4dfc0517b9d4bb3f8ed.pdf' and (text() = 'Policy Contract' or . = 'Policy Contract')]</value>
      <webElementGuid>41e458e0-c318-4b9a-a3ab-e53ec7a474c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
