<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Declaration</name>
   <tag></tag>
   <elementGuidId>e618e112-f44d-4524-b21a-1288bd5bebd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/tripcare360/static/Declaration_EGIB_En-7677727f03a4416fce97cc032ca03e1f.pdf' and (text() = 'Declaration' or . = 'Declaration')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@aria-label='form-declaration']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9c149800-2a16-4f5f-9518-06e20caefd8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-link</value>
      <webElementGuid>4de13855-ba36-4288-8a54-67192ae6618c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tripcare360/static/Declaration_EGIB_En-7677727f03a4416fce97cc032ca03e1f.pdf</value>
      <webElementGuid>fb770dd9-5abd-4b9c-9b12-e147cb46330a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>e154ae69-3367-46b9-8c4f-4594c5921b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>form-declaration</value>
      <webElementGuid>36a09cca-c95d-44f9-b30c-bf9a966e30a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noreferrer</value>
      <webElementGuid>1eb81e14-99b4-435d-9187-08b33d05d9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Declaration</value>
      <webElementGuid>578fb144-95b1-4b45-b823-4a748f7a1405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;Layout__Styles-sc-d7vu2k-0 fGSPvF&quot;]/div[@class=&quot;review__Styles-sc-1y5xbh0-1 jrSuyi&quot;]/div[@class=&quot;mt-3 container&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-7 col-12&quot;]/div[@class=&quot;DeclarationForm__DeclarationDiv-sc-4vr836-4 hXczvA&quot;]/div[@class=&quot;box-container p-2 card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;DeclarationForm__Styles-sc-4vr836-0 jaeJwV&quot;]/div[@class=&quot;card.text&quot;]/div[1]/div[@class=&quot;d-flex gap-3&quot;]/div[2]/a[@class=&quot;a-link&quot;]</value>
      <webElementGuid>5c08ebfd-b1cc-4f2a-89b3-cc0bb687f075</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div/form/div/div/div[4]/div[2]/div/div/div/div/div[2]/div[2]/a[4]</value>
      <webElementGuid>b8269dd0-9d65-4c83-a7b6-43a8baf2d9f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Declaration')]</value>
      <webElementGuid>194eb71f-5f56-44ae-aaec-4ecda864ea34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Important Notice'])[1]/following::a[1]</value>
      <webElementGuid>c50db44a-3ee9-41ce-b8b6-926d261331cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Policy Contract'])[1]/following::a[2]</value>
      <webElementGuid>6a05e98f-de1f-4a71-8681-0f1d092377fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PIDM’s TIPS Brochure'])[1]/preceding::a[1]</value>
      <webElementGuid>cc3e9392-e044-4246-b7fd-243c49df1843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='www.pidm.gov.my'])[1]/preceding::a[2]</value>
      <webElementGuid>bf03646e-0032-43eb-9363-88f3c2ae5cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/tripcare360/static/Declaration_Eng_Ins-1e396d98aa057d554ef7884e1d1c57b7.pdf')]</value>
      <webElementGuid>48a053f3-a3d0-4a7d-acb0-623d642f8a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>5c6b4324-500d-43a8-9b82-988ae82b5b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/tripcare360/static/Declaration_Eng_Ins-1e396d98aa057d554ef7884e1d1c57b7.pdf' and (text() = 'Declaration' or . = 'Declaration')]</value>
      <webElementGuid>cde921c9-7046-4852-b6bd-b1523e5cc1e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
