<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_ProductDisclosureSheet</name>
   <tag></tag>
   <elementGuidId>0ea39788-8e0a-4c00-bbc2-113d223c4523</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@aria-label='disclosure-sheet']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/tripcare360/static/PMG_EGIB_TC360_PDS_ENG_ECHANNEL_DIRECT_2308V1.0-8d55f808fad416d55e41ca03118ee5be.pdf' and (text() = ' Product Disclosure Sheet' or . = ' Product Disclosure Sheet')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.a-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>11bbb02a-0616-48b6-81dc-e63699e60c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-link</value>
      <webElementGuid>5a10389b-3cf8-4726-b20b-fa0409f318da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tripcare360/static/PMG_EGIB_TC360_PDS_ENG_ECHANNEL_DIRECT_2308V1.0-8d55f808fad416d55e41ca03118ee5be.pdf</value>
      <webElementGuid>7da8d5be-059b-4256-a561-5eb908d0fefc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>704d6811-bcc5-4bbb-b0b5-473108100744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
      <webElementGuid>24363e04-546f-4ceb-8bfc-90aa1ea8de68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>disclosure-sheet</value>
      <webElementGuid>7a99ca08-58f9-4334-9dd5-7ef0646db43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Product Disclosure Sheet</value>
      <webElementGuid>d5980921-c045-49b0-8dd1-c2c58624aa91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;Layout__Styles-sc-d7vu2k-0 fGSPvF&quot;]/div[@class=&quot;review__Styles-sc-1y5xbh0-1 jrSuyi&quot;]/div[@class=&quot;mt-3 container&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-7 col-12&quot;]/div[@class=&quot;DeclarationForm__DeclarationDiv-sc-4vr836-4 hXczvA&quot;]/div[@class=&quot;box-container p-2 card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;DeclarationForm__Styles-sc-4vr836-0 jaeJwV&quot;]/div[@class=&quot;card.text&quot;]/div[1]/div[@class=&quot;d-flex gap-3&quot;]/div[2]/a[@class=&quot;a-link&quot;]</value>
      <webElementGuid>cc29d048-f59d-43b2-98d1-b371eff6e477</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div/form/div/div/div[4]/div[2]/div/div/div/div/div[2]/div[2]/a</value>
      <webElementGuid>7b218d9e-f9e5-45e6-ada9-3784467a4262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Product Disclosure Sheet')]</value>
      <webElementGuid>0efda3f5-2717-4bd8-8f8a-544dee42021b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I confirm that I have read and agree to the'])[1]/following::a[1]</value>
      <webElementGuid>1e24caaa-b69d-444f-99ac-360cc4cf7a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Policy Contract'])[1]/preceding::a[1]</value>
      <webElementGuid>665b23ba-5704-442f-ad8d-497b13c77d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Important Notice'])[1]/preceding::a[2]</value>
      <webElementGuid>39d5fe21-a54b-45bc-85ae-5eed7c824dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Product Disclosure Sheet']/parent::*</value>
      <webElementGuid>8b159cd3-a31b-47af-af0c-adf13cf1d3ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/tripcare360/static/PMG_EGIB_TC360_PDS_ENG_ECHANNEL_DIRECT_2308V1.0-8d55f808fad416d55e41ca03118ee5be.pdf')]</value>
      <webElementGuid>f6cab0e4-c78a-46ac-b5ea-a01f6e430373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>491ced4d-d5e6-4bf7-8d58-9e8eccf63065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/tripcare360/static/PMG_EGIB_TC360_PDS_ENG_ECHANNEL_DIRECT_2308V1.0-8d55f808fad416d55e41ca03118ee5be.pdf' and (text() = ' Product Disclosure Sheet' or . = ' Product Disclosure Sheet')]</value>
      <webElementGuid>ab19cd54-ec36-43b8-b0de-b101aef5469c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
