<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rdoAMEX</name>
   <tag></tag>
   <elementGuidId>7d430821-873d-467b-8be1-be15d771d322</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='AMEX']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'payMode' and @type = 'radio' and @id = 'CARD']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CARD</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74f10577-af52-41b2-9b42-9ed0081df1ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payMode</value>
      <webElementGuid>9937663f-32b8-4230-a95f-8b73b6dfa437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2f5a554d-837f-4d28-af0b-d361c6e537dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CARD</value>
      <webElementGuid>0494f71b-b36f-462b-a60b-049e3218aad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>462e0725-0c31-46c7-90f0-5ff1071e0567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>CARD</value>
      <webElementGuid>32e144ee-87a2-45a9-88d6-b459437e4855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CARD&quot;)</value>
      <webElementGuid>11160d16-13f1-4def-b1b5-1707a6211b47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CARD']</value>
      <webElementGuid>90e72f42-2db9-4197-b5e9-0398a769a913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div/form/div/div/div[3]/div[2]/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>c63c65d2-26b1-4153-b059-86dfa434f4f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>fed63078-74bd-4c1a-95e1-8f69d891a2cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'payMode' and @type = 'radio' and @id = 'CARD']</value>
      <webElementGuid>0a19c7d5-27e1-4e10-905e-ff3e5b138881</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
