<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rdoAMEX</name>
   <tag></tag>
   <elementGuidId>7d430821-873d-467b-8be1-be15d771d322</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CARD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AMEX']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'payMode' and @type = 'radio' and @id = 'CARD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ba9390a-c14d-475a-acba-a0175fda7363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payMode</value>
      <webElementGuid>f5045763-773e-4fc1-a647-667167f9ffb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5852c54b-781c-4370-a1ba-60ed67a354fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CARD</value>
      <webElementGuid>df4a9ba7-34d9-41aa-992e-cf59c070c848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>360f8e2d-2b05-463d-895c-e128c1a4b2a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>CARD</value>
      <webElementGuid>c466fd1a-c171-4226-8e40-9883b317e0c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CARD&quot;)</value>
      <webElementGuid>53b62a57-f506-4997-b08f-a037cf74de9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CARD']</value>
      <webElementGuid>784f76d1-c036-4ce8-a35b-586148cc23b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div/form/div/div/div[3]/div[2]/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>22cab0f7-6b53-47fa-8f4e-dba4ec9295a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4ce96af4-b103-4407-8894-39b76220bd26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'payMode' and @type = 'radio' and @id = 'CARD']</value>
      <webElementGuid>b659df69-03a7-49d5-bb28-b5bf6901e34b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
