<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rdoFPXPayment</name>
   <tag></tag>
   <elementGuidId>3a977015-6368-4f5b-b47d-e3cde88a1f11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FPX</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FPX']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'payMode' and @type = 'radio' and @id = 'FPX']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>657f35e3-1656-45d2-a602-9255686e73e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payMode</value>
      <webElementGuid>ce9091ff-9f8f-4534-b38a-52071ee9882a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6bd38caf-0cb6-4fbf-9f0e-dd7e82cc043f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FPX</value>
      <webElementGuid>17e48c9f-4f97-4963-847a-6d9502ed76ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>2137a58a-4bd0-4568-a65c-579a4533086e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>FPX</value>
      <webElementGuid>b98701de-4fa8-45fe-a97f-f1f0ca64d4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FPX&quot;)</value>
      <webElementGuid>f47982ee-13a7-4a18-b5ce-0c22ec2aa84d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FPX']</value>
      <webElementGuid>affa2209-a1e2-48fc-aec4-1f1509d7e257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div/form/div/div/div[3]/div[2]/div/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>f8cf5fb1-e272-4c9e-8536-dfdcf5b28ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>0d58fe9d-0fd1-4a3a-af9f-ddbe90aecc29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'payMode' and @type = 'radio' and @id = 'FPX']</value>
      <webElementGuid>5e8a8594-84f8-426d-9593-f87b4c452c61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
