<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rdoVisaMasterCard</name>
   <tag></tag>
   <elementGuidId>e8371896-b0fb-410f-9517-b423b0650453</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CARD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CARD']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'payMode' and @type = 'radio' and @id = 'CARD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>395ba07b-5bc0-4da4-8365-ffb07d0eb23f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payMode</value>
      <webElementGuid>d490050f-1091-4037-b702-45c64d2045eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ecd7ecde-6695-48b0-bb84-079dbb8d903f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CARD</value>
      <webElementGuid>102cf5b5-6f9a-4444-9c05-d9f922ced875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>de88206e-884f-4fd6-817e-80a8ed58fc60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>CARD</value>
      <webElementGuid>783454fc-5620-480b-ae1b-fa4ef8d3e9ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CARD&quot;)</value>
      <webElementGuid>507a4087-e4f6-4bf5-9952-b7f1e8f98712</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CARD']</value>
      <webElementGuid>f83b72fa-1120-4fde-abad-1d39b342c332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div/form/div/div/div[3]/div[2]/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>43868854-3898-4e51-b054-f8f160dadae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>af57abfb-c672-4517-9bd1-6a5b49317fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'payMode' and @type = 'radio' and @id = 'CARD']</value>
      <webElementGuid>9ad8b8c0-9a08-48b1-961b-c5943bbc9ab7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
