<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close Personal Details</name>
   <tag></tag>
   <elementGuidId>1b305ef5-9601-4d99-9924-5ae73ad15ba7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[contains(@class,'PersonalDetailsForm__Buttons-sc-fng3b1-1')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>8138a46e-beb7-445a-8f47-dd605d701a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1735550535205</value>
      <webElementGuid>538c6c3a-b7f8-4abf-99a7-864170e676a7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
