<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Marital Status_Single</name>
   <tag></tag>
   <elementGuidId>2577d333-e2ef-47b1-a918-0e38ae254b81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='maritalStatus']/parent::*//descendant::a[text()='Single']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>ceb9f02a-f89b-4811-90cd-36553b15cf53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1735782991058</value>
      <webElementGuid>d3e693be-dc65-4e1a-b888-f7c6ccb95aba</webElementGuid>
   </webElementProperties>
</WebElementEntity>
