<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save Personal Details</name>
   <tag></tag>
   <elementGuidId>3518927e-5e5e-47a2-9caf-1da4f6ec28de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[contains(@class,'PersonalDetailsForm__Buttons-sc-fng3b1-1')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>34cf50b1-159e-46b8-824d-3f6ec3124783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1735550464640</value>
      <webElementGuid>95f596d7-fe2b-4ce1-90cc-fcbe449fd1df</webElementGuid>
   </webElementProperties>
</WebElementEntity>
