<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_AddStorey</name>
   <tag></tag>
   <elementGuidId>d909e011-74d4-4b54-9047-9965af369f16</elementGuidId>
   <imagePath>img/Minus.png</imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>img/Minus.png</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@class,'plusCircle_svg__bi')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
</WebElementEntity>
