<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dyinput_detailWithoutIdentifier_detail</name>
   <tag></tag>
   <elementGuidId>d2b868ed-e947-4612-b4ef-19535e5f027a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[contains(@class, 'form-label') and contains(text(), '${detail}')]//following-sibling::*//descendant::input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.TextInput__FormControl-sc-11abdq8-0.gIXGyq.undefined.undefined.form-control</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Vehicle Number$/ >> internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90d9b5dc-c2e7-4a61-8dee-f39ca9c956da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2646f31d-9ea9-46ad-b1bd-94dc95db20d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextInput__FormControl-sc-11abdq8-0 gIXGyq undefined undefined form-control</value>
      <webElementGuid>eb949c9d-71ca-4e28-8e73-f03eab6ff77f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>VOA0010</value>
      <webElementGuid>2b3d09d4-cad6-4641-8b95-7c8db9311b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;layout__Styles-sc-csgnm7-0 iJzkTS&quot;]/div[@class=&quot;application__Styles-sc-1nz1bvy-0 dGLBAc bg-white&quot;]/form[1]/div[@class=&quot;container-padding-hide container&quot;]/div[@class=&quot;g-3 row&quot;]/div[@class=&quot;col-lg-6 col-md-8 col-12&quot;]/div[@class=&quot;application__StyledAccordion-sc-1nz1bvy-1 jZLTqu accordion&quot;]/div[@class=&quot;application__AccordionItem-sc-1nz1bvy-2 dtTcdK accordion-item&quot;]/div[@class=&quot;accordion-collapse collapse show&quot;]/div[@class=&quot;accordion-body&quot;]/div[1]/form[1]/div[@class=&quot;d-flex gap-3 row&quot;]/div[1]/div[@class=&quot;input-group&quot;]/input[@class=&quot;TextInput__FormControl-sc-11abdq8-0 gIXGyq undefined undefined form-control&quot;]</value>
      <webElementGuid>9cbc9bd5-3221-4e22-8eb3-87e7cd543333</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='VOA0010']</value>
      <webElementGuid>c6c5a23e-f784-470d-8629-9cf611a9f745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/form/div/div/div[2]/div/div/div/div/div/form/div/div/div/input</value>
      <webElementGuid>a6820697-1e64-4f46-8866-3a055d6af89a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a5712004-f8e0-47df-b715-7444f81cced3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>975d173d-b106-4707-a2fc-10c4a74b31a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
