<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email</name>
   <tag></tag>
   <elementGuidId>5e009dc9-0bae-4201-95da-1d891d593590</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='personalDetails.email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;personalDetails.email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;E.G. : ADAM@GMAIL.COM&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>862efdbe-5a19-43af-b365-299780d65557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>E.G. : ADAM@GMAIL.COM</value>
      <webElementGuid>17137c30-fa80-429a-8a00-2ce7dc2956d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>824b2bf7-d3c2-431e-8c5d-f59910a11d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personalDetails.email</value>
      <webElementGuid>879b342d-f92b-4da2-8483-fd349b415f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>10c55bfe-09e9-48c5-827a-b695f52ac5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextInput__FormControl-sc-11abdq8-0 fGRBTk undefined undefined form-control</value>
      <webElementGuid>6900456f-cc27-4869-927e-3df2f666e224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;layout__Styles-sc-csgnm7-0 iJzkTS&quot;]/div[@class=&quot;application__Styles-sc-1nz1bvy-0 dGLBAc bg-white&quot;]/form[1]/div[@class=&quot;container-padding-hide container&quot;]/div[@class=&quot;g-3 row&quot;]/div[@class=&quot;col-lg-6 col-md-8 col-12&quot;]/div[@class=&quot;application__StyledAccordion-sc-1nz1bvy-1 jZLTqu accordion&quot;]/div[@class=&quot;application__AccordionItem-sc-1nz1bvy-2 dtTcdK accordion-item&quot;]/div[@class=&quot;accordion-collapse collapse show&quot;]/div[@class=&quot;accordion-body&quot;]/div[1]/form[1]/div[@class=&quot;gap-3 row&quot;]/div[9]/div[@class=&quot;input-group&quot;]/input[@class=&quot;TextInput__FormControl-sc-11abdq8-0 fGRBTk undefined undefined form-control&quot;]</value>
      <webElementGuid>52662ea1-c7df-45c2-a808-eb91ad9f2d42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='personalDetails.email']</value>
      <webElementGuid>a5068571-d506-4b30-bcfd-08e87c8d2f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/form/div/div/div[2]/div/div[2]/div/div/div/form/div/div[9]/div/input</value>
      <webElementGuid>947c593f-e06b-47f5-b9a4-e7173dfbada6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>1a5d8723-b94c-4d07-b27f-9977c9787a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'E.G. : ADAM@GMAIL.COM' and @name = 'personalDetails.email' and @type = 'text']</value>
      <webElementGuid>128a2ea1-2999-4200-90fa-74999ba7721e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
