<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_mobileNumber</name>
   <tag></tag>
   <elementGuidId>6a61b37c-595d-4782-b0d4-50881fde7d10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='personalDetails.mobileNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;personalDetails.mobileNo&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;123456789&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf762284-b73c-472c-b787-4bd548a18a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>123456789</value>
      <webElementGuid>9c06c63a-5d60-4435-8fc4-eb6707763b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>c0f67a7d-6993-444e-9277-a3c178bd1aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personalDetails.mobileNo</value>
      <webElementGuid>e9f31114-8a27-428f-b922-faac8805d83a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>be3745d7-745b-4d8f-9125-bd2a3934c01e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextInput__FormControl-sc-11abdq8-0 fGRBTk undefined undefined form-control</value>
      <webElementGuid>e5d54066-cefe-4af0-9ba2-9990b0f67bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;layout__Styles-sc-csgnm7-0 iJzkTS&quot;]/div[@class=&quot;application__Styles-sc-1nz1bvy-0 dGLBAc bg-white&quot;]/form[1]/div[@class=&quot;container-padding-hide container&quot;]/div[@class=&quot;g-3 row&quot;]/div[@class=&quot;col-lg-6 col-md-8 col-12&quot;]/div[@class=&quot;application__StyledAccordion-sc-1nz1bvy-1 jZLTqu accordion&quot;]/div[@class=&quot;application__AccordionItem-sc-1nz1bvy-2 dtTcdK accordion-item&quot;]/div[@class=&quot;accordion-collapse collapse show&quot;]/div[@class=&quot;accordion-body&quot;]/div[1]/form[1]/div[@class=&quot;gap-3 row&quot;]/div[8]/div[@class=&quot;input-group&quot;]/input[@class=&quot;TextInput__FormControl-sc-11abdq8-0 fGRBTk undefined undefined form-control&quot;]</value>
      <webElementGuid>8a532474-5d26-4545-a5ec-6ab0ba889305</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='personalDetails.mobileNo']</value>
      <webElementGuid>2826be37-3fcc-4c9f-a649-7cb6eb654b10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/form/div/div/div[2]/div/div[2]/div/div/div/form/div/div[8]/div/input</value>
      <webElementGuid>6a27ac00-7b54-4601-980e-81b878eb01bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>354be2bd-2199-4543-974f-985401d09b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '123456789' and @name = 'personalDetails.mobileNo' and @type = 'text']</value>
      <webElementGuid>62a2ee05-e06c-483a-ace0-a6c84a99f93e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
