<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_address2</name>
   <tag></tag>
   <elementGuidId>ff8b6112-b837-416f-89eb-3cb05cabcd6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='homeAddress.addressLine2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;homeAddress.addressLine2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;E.G. ADDRESS LINE 2&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46c00f5a-f8aa-407b-833f-f174d8a247d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>E.G. ADDRESS LINE 2</value>
      <webElementGuid>d92c8471-a640-4948-9016-3acfcec7e2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>b6c9ce29-ef1a-4f56-bebf-7fd4b6d7b612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>homeAddress.addressLine2</value>
      <webElementGuid>686a9951-e23b-49ff-87e9-b6b9afc5737b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>34e4b7f0-3f00-4495-8d98-c04e89407c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextInput__FormControl-sc-11abdq8-0 fGRBTk undefined undefined form-control</value>
      <webElementGuid>a4d82f51-8f7d-40cf-9a9d-83f5b6e623d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;layout__Styles-sc-csgnm7-0 iJzkTS&quot;]/div[@class=&quot;application__Styles-sc-1nz1bvy-0 dGLBAc bg-white&quot;]/form[1]/div[@class=&quot;container-padding-hide container&quot;]/div[@class=&quot;g-3 row&quot;]/div[@class=&quot;col-lg-6 col-md-8 col-12&quot;]/div[@class=&quot;application__StyledAccordion-sc-1nz1bvy-1 jZLTqu accordion&quot;]/div[@class=&quot;application__AccordionItem-sc-1nz1bvy-2 dtTcdK accordion-item&quot;]/div[@class=&quot;accordion-collapse collapse show&quot;]/div[@class=&quot;accordion-body&quot;]/div[1]/form[1]/div[@class=&quot;gap-3 row&quot;]/div[12]/div[@class=&quot;input-group&quot;]/input[@class=&quot;TextInput__FormControl-sc-11abdq8-0 fGRBTk undefined undefined form-control&quot;]</value>
      <webElementGuid>622e4107-a498-4794-8b24-e285afca14c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='homeAddress.addressLine2']</value>
      <webElementGuid>38825e5f-bb44-40c9-ac5b-6198734ddd93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/form/div/div/div[2]/div/div[2]/div/div/div/form/div/div[12]/div/input</value>
      <webElementGuid>5a01d618-ca3c-465b-bf18-44d5c2b5ec2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/input</value>
      <webElementGuid>f9cf18f4-ddad-41cd-8bdf-b98eccfc5f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'E.G. ADDRESS LINE 2' and @name = 'homeAddress.addressLine2' and @type = 'text']</value>
      <webElementGuid>02150696-5072-44f2-9302-77dbf62e75e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
