<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_name</name>
   <tag></tag>
   <elementGuidId>9e7a0c81-cafe-4bcc-a8f9-8c533d6ad2c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='personalDetails.name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;personalDetails.name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;E.G. : ADAM BIN BAKRI&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a54ad6a1-4a8a-4b0a-b888-b934b6fa7c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>E.G. : ADAM BIN BAKRI</value>
      <webElementGuid>d5177cc1-78cb-47ad-9cc0-094f83e31ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personalDetails.name</value>
      <webElementGuid>c8cd03e3-58bd-4da8-8ce2-f89c1d03ec51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1ff0d8c2-8229-45af-98e5-cdc79129f334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextInput__FormControl-sc-11abdq8-0 fGRBTk undefined undefined form-control</value>
      <webElementGuid>ff88098d-a02f-42ea-97a1-00a04bdc1fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;layout__Styles-sc-csgnm7-0 iJzkTS&quot;]/div[@class=&quot;application__Styles-sc-1nz1bvy-0 dGLBAc bg-white&quot;]/form[1]/div[@class=&quot;container-padding-hide container&quot;]/div[@class=&quot;g-3 row&quot;]/div[@class=&quot;col-lg-6 col-md-8 col-12&quot;]/div[@class=&quot;application__StyledAccordion-sc-1nz1bvy-1 jZLTqu accordion&quot;]/div[@class=&quot;application__AccordionItem-sc-1nz1bvy-2 dtTcdK accordion-item&quot;]/div[@class=&quot;accordion-collapse collapse show&quot;]/div[@class=&quot;accordion-body&quot;]/div[1]/form[1]/div[@class=&quot;gap-3 row&quot;]/div[1]/div[@class=&quot;input-group&quot;]/input[@class=&quot;TextInput__FormControl-sc-11abdq8-0 fGRBTk undefined undefined form-control&quot;]</value>
      <webElementGuid>a616813d-9231-4baa-b52a-bd7b0555b520</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='personalDetails.name']</value>
      <webElementGuid>940c03bd-de33-4659-bdce-e8b24dfbe403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/form/div/div/div[2]/div/div[2]/div/div/div/form/div/div/div/input</value>
      <webElementGuid>40b4bbe6-ab39-4586-b5fd-64765f53df1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/form/div/div/div/input</value>
      <webElementGuid>7d19dc50-b1ca-4a41-98c7-fdf9b5c43a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'E.G. : ADAM BIN BAKRI' and @name = 'personalDetails.name' and @type = 'text']</value>
      <webElementGuid>8467c0eb-9339-4e8d-81a1-59b5a10d6813</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
