<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PropertyDetailsPostcode</name>
   <tag></tag>
   <elementGuidId>25e89523-e827-45e0-b50c-a8deeb3ca4ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;propertyDetails.address.postcode&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='propertyDetails.address.postcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;propertyDetails\.address\.postcode&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>545d7a31-e1d9-4a2f-8671-48946b411573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>E.G. 68100</value>
      <webElementGuid>79927f59-5076-4fdc-a1fc-6b708d693d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>1e105f35-1804-4dd1-b90c-09ae107bffc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>1877058f-76af-4b28-af93-75f1c24c5282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>propertyDetails.address.postcode</value>
      <webElementGuid>69a79b82-7601-43e1-8e6b-b1a97688f26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c77a7143-9091-461e-bb43-815edcd96fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextInput__FormControl-sc-l1yoz3-0 jHNbic undefined undefined form-control</value>
      <webElementGuid>85e9a622-9fae-4b86-838f-bba701d73468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;layout__Styles-sc-wetbic-0 ehlvJr&quot;]/div[@class=&quot;application__Styles-sc-n77imq-0 bDraSB bg-white&quot;]/form[1]/div[@class=&quot;container-padding-hide container&quot;]/div[@class=&quot;g-3 row&quot;]/div[@class=&quot;col-lg-6 col-md-8 col-12&quot;]/div[@class=&quot;application__StyledAccordion-sc-n77imq-1 gnSTuM accordion&quot;]/div[@class=&quot;application__AccordionItem-sc-n77imq-2 gxLUjU accordion-item&quot;]/div[@class=&quot;accordion-collapse collapse show&quot;]/div[@class=&quot;accordion-body&quot;]/div[@class=&quot;g-3 row&quot;]/div[@class=&quot;TextInput__FormGroup-sc-l1yoz3-1 ekGFlN&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;TextInput__FormControl-sc-l1yoz3-0 jHNbic undefined undefined form-control&quot;]</value>
      <webElementGuid>933ae2b4-1da4-4234-bb2b-4feb1ba4fb9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='propertyDetails.address.postcode']</value>
      <webElementGuid>51b5f159-c063-459c-bd2f-2e654d9d9e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/form/div/div/div[2]/div/div[2]/div/div/div/div[4]/div/input</value>
      <webElementGuid>4f88b5b5-fb9c-4199-81a5-2f4bd799361c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>38fd877c-a419-4a53-8163-84d32a6c52ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'E.G. 68100' and @name = 'propertyDetails.address.postcode' and @type = 'text']</value>
      <webElementGuid>d8f2f7a2-e55a-44ba-86b6-4043310ef32e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
