<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name</name>
   <tag></tag>
   <elementGuidId>66d6a08e-2e7a-4641-a981-2221d3919368</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;personalDetails.name&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='personalDetails.name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;E.G. : ADAM BIN BAKRI&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3db62f8f-7159-41e0-a6da-6c9db0c1fbb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>E.G. : ADAM BIN BAKRI</value>
      <webElementGuid>79eff145-348b-49e5-a5ae-33e66019aad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personalDetails.name</value>
      <webElementGuid>4dac3373-ae49-479c-9273-22934cdf4546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d88fc8c3-554f-4d15-972f-2aa8f8fff123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextInput__FormControl-sc-l1yoz3-0 jHNbic undefined undefined form-control</value>
      <webElementGuid>628d5764-bd46-4e42-b35a-96abeb776e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;layout__Styles-sc-wetbic-0 ehlvJr&quot;]/div[@class=&quot;application__Styles-sc-n77imq-0 bDraSB bg-white&quot;]/form[1]/div[@class=&quot;container-padding-hide container&quot;]/div[@class=&quot;g-3 row&quot;]/div[@class=&quot;col-lg-6 col-md-8 col-12&quot;]/div[@class=&quot;application__StyledAccordion-sc-n77imq-1 gnSTuM accordion&quot;]/div[@class=&quot;application__AccordionItem-sc-n77imq-2 gxLUjU accordion-item&quot;]/div[@class=&quot;accordion-collapse collapse show&quot;]/div[@class=&quot;accordion-body&quot;]/div[1]/form[1]/div[@class=&quot;d-flex gap-3 row&quot;]/div[@class=&quot;TextInput__FormGroup-sc-l1yoz3-1 ekGFlN&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;TextInput__FormControl-sc-l1yoz3-0 jHNbic undefined undefined form-control&quot;]</value>
      <webElementGuid>4afe3d22-3731-458a-9c03-009437b2749b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='personalDetails.name']</value>
      <webElementGuid>0e0517bc-d4af-48fd-8e26-d15988c931fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/form/div/div/div[2]/div/div/div/div/div/form/div/div/div/input</value>
      <webElementGuid>4aac7eca-3dfe-41e4-93d4-7be0c6ec53d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d7e88d18-d7b8-4425-8499-cf94d8622b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'E.G. : ADAM BIN BAKRI' and @name = 'personalDetails.name' and @type = 'text']</value>
      <webElementGuid>5ca054e2-84a8-4360-a916-fdfd68bfe208</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
