<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email</name>
   <tag></tag>
   <elementGuidId>e0e9c2e6-9a92-4e87-83f3-0dd1bfd58f44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;personalDetails.email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='personalDetails.email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;E.G. : ADAM@GMAIL.COM&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2aa104ed-2663-4750-904e-965e19a3cecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>E.G. : ADAM@GMAIL.COM</value>
      <webElementGuid>f478835a-a69f-4d65-8480-150c584ab244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>8cf10cf1-dd23-4283-ac32-c20c331a6529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>personalDetails.email</value>
      <webElementGuid>5f0a54e1-7c33-4880-b237-3987f7a440bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>80d7ced4-4b16-43df-866f-eb58b1c5c603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextInput__FormControl-sc-l1yoz3-0 jHNbic undefined undefined form-control</value>
      <webElementGuid>77859141-6511-4dfb-82b7-33fc23c1872c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;layout__Styles-sc-wetbic-0 ehlvJr&quot;]/div[@class=&quot;application__Styles-sc-n77imq-0 bDraSB bg-white&quot;]/form[1]/div[@class=&quot;container-padding-hide container&quot;]/div[@class=&quot;g-3 row&quot;]/div[@class=&quot;col-lg-6 col-md-8 col-12&quot;]/div[@class=&quot;application__StyledAccordion-sc-n77imq-1 gnSTuM accordion&quot;]/div[@class=&quot;application__AccordionItem-sc-n77imq-2 gxLUjU accordion-item&quot;]/div[@class=&quot;accordion-collapse collapse show&quot;]/div[@class=&quot;accordion-body&quot;]/div[1]/form[1]/div[@class=&quot;d-flex gap-3 row&quot;]/div[@class=&quot;TextInput__FormGroup-sc-l1yoz3-1 ekGFlN&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;TextInput__FormControl-sc-l1yoz3-0 jHNbic undefined undefined form-control&quot;]</value>
      <webElementGuid>5e052df4-2f67-43fb-8f3d-be4680c514d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='personalDetails.email']</value>
      <webElementGuid>fd5ad391-b4de-4337-9aec-086f969d5d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/form/div/div/div[2]/div/div/div/div/div/form/div/div[9]/div/input</value>
      <webElementGuid>d31f62cd-0177-4ffb-ba3b-ccc6a142ba5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>4f15a044-b714-4344-8923-ae056fe06fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'E.G. : ADAM@GMAIL.COM' and @name = 'personalDetails.email' and @type = 'text']</value>
      <webElementGuid>98e62ff9-889a-44b5-9336-fddfeae1aa02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
