<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PropertyDetailsAddress1</name>
   <tag></tag>
   <elementGuidId>7bd915b5-bda0-4fef-9216-fbe933e24bae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;propertyDetails.address.addressLine1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='propertyDetails.address.addressLine1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;propertyDetails\.address\.addressLine1&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6eab3aa2-5744-4286-b077-5fdf4e2e2300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>E.G. ADDRESS LINE 1</value>
      <webElementGuid>f8a6b373-f05b-44fe-ba69-4fc564f37b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>4a6c9a67-9f09-4f02-af4d-1f4d9fd3b512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>propertyDetails.address.addressLine1</value>
      <webElementGuid>5f951e2e-6a4e-477c-b8d1-3e0288c6a4d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5b667b77-d779-4914-b285-852dfd2dcfd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextInput__FormControl-sc-l1yoz3-0 jHNbic undefined undefined form-control</value>
      <webElementGuid>693d2ca7-ccfd-4440-b56a-a07446e1e082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;layout__Styles-sc-wetbic-0 ehlvJr&quot;]/div[@class=&quot;application__Styles-sc-n77imq-0 bDraSB bg-white&quot;]/form[1]/div[@class=&quot;container-padding-hide container&quot;]/div[@class=&quot;g-3 row&quot;]/div[@class=&quot;col-lg-6 col-md-8 col-12&quot;]/div[@class=&quot;application__StyledAccordion-sc-n77imq-1 gnSTuM accordion&quot;]/div[@class=&quot;application__AccordionItem-sc-n77imq-2 gxLUjU accordion-item&quot;]/div[@class=&quot;accordion-collapse collapse show&quot;]/div[@class=&quot;accordion-body&quot;]/div[@class=&quot;g-3 row&quot;]/div[@class=&quot;TextInput__FormGroup-sc-l1yoz3-1 ekGFlN&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;TextInput__FormControl-sc-l1yoz3-0 jHNbic undefined undefined form-control&quot;]</value>
      <webElementGuid>50892bef-a506-470a-996e-5f1b3909b49a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='propertyDetails.address.addressLine1']</value>
      <webElementGuid>f70b1170-d596-41e0-8440-2a529877f19b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/form/div/div/div[2]/div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>ff91d30b-2cac-48bf-a2b8-6c820aabf670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>a279b273-82be-42cf-a5e1-f89c1470bcc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'E.G. ADDRESS LINE 1' and @name = 'propertyDetails.address.addressLine1' and @type = 'text']</value>
      <webElementGuid>43ffafd6-2728-4573-b859-2fb8bc8bdb94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
