<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PropertyDetailsAddress2</name>
   <tag></tag>
   <elementGuidId>822bb8bb-2a83-40a6-901f-3ca0c7be6a12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;propertyDetails.address.addressLine2&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='propertyDetails.address.addressLine2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;propertyDetails\.address\.addressLine2&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1cc090d3-44d5-41c9-8165-bd7e4f4d6fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>E.G. ADDRESS LINE 2</value>
      <webElementGuid>8e2ed71e-581d-4daa-ad2c-e448436169e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>4014efc8-ee45-4074-8dc1-55f04c07e6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>propertyDetails.address.addressLine2</value>
      <webElementGuid>9513f5d2-32a8-4516-ae0c-c7208cb91328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4d7c2f0e-b87e-4d5a-949a-3931932187a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextInput__FormControl-sc-l1yoz3-0 jHNbic undefined undefined form-control</value>
      <webElementGuid>727771f6-d0a7-4cdc-9348-32ef3a077f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;layout__Styles-sc-wetbic-0 ehlvJr&quot;]/div[@class=&quot;application__Styles-sc-n77imq-0 bDraSB bg-white&quot;]/form[1]/div[@class=&quot;container-padding-hide container&quot;]/div[@class=&quot;g-3 row&quot;]/div[@class=&quot;col-lg-6 col-md-8 col-12&quot;]/div[@class=&quot;application__StyledAccordion-sc-n77imq-1 gnSTuM accordion&quot;]/div[@class=&quot;application__AccordionItem-sc-n77imq-2 gxLUjU accordion-item&quot;]/div[@class=&quot;accordion-collapse collapse show&quot;]/div[@class=&quot;accordion-body&quot;]/div[@class=&quot;g-3 row&quot;]/div[@class=&quot;TextInput__FormGroup-sc-l1yoz3-1 ekGFlN&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;TextInput__FormControl-sc-l1yoz3-0 jHNbic undefined undefined form-control&quot;]</value>
      <webElementGuid>f6826ffc-e5e7-4f2d-a9b8-6118e688e873</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='propertyDetails.address.addressLine2']</value>
      <webElementGuid>ba600f83-d328-41d3-859c-8f6851bce95c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/form/div/div/div[2]/div/div[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>2b61574f-d1cc-4d77-891c-27577bc821c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>b63df80b-ffc7-4d58-902c-2343600d3c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'E.G. ADDRESS LINE 2' and @name = 'propertyDetails.address.addressLine2' and @type = 'text']</value>
      <webElementGuid>69a496fe-9c35-47cc-b1c4-936926777c36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
