<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Discount</name>
   <tag></tag>
   <elementGuidId>f79d0d08-5a29-4cd5-b285-982ebe836593</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='col-5']//descendant::div[starts-with(text(), 'Discount ')]//following-sibling::div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>832851c9-04ef-47d9-b9e5-bba049f4bfa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1735551540431</value>
      <webElementGuid>58b10147-4a70-4e95-9887-7c59e7543028</webElementGuid>
   </webElementProperties>
</WebElementEntity>
