<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_NCD</name>
   <tag></tag>
   <elementGuidId>87bcc1f5-ce66-4d26-858f-a298bf2efddc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='col-5']//descendant::div[contains(text(), 'NCD')]//following-sibling::div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>3a8ac225-488e-4b1d-b21e-29cc1e9f7be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1735551503850</value>
      <webElementGuid>6577c375-cd04-48bd-a39b-d2d1aec2b045</webElementGuid>
   </webElementProperties>
</WebElementEntity>
