<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_nextMonth Flight</name>
   <tag></tag>
   <elementGuidId>c7ae6f07-f1a0-490f-8461-1f07236799c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;next-month&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='next-month']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>57d47996-9547-456b-9213-9bea83077452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>next-month</value>
      <webElementGuid>5558546a-f5db-411d-bdaf-fb65606ba4f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Go to next month</value>
      <webElementGuid>61eb896d-2076-4fa4-8c22-a79c273c9719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rdp-button_reset rdp-button rdp-nav_button rdp-nav_button_next</value>
      <webElementGuid>3c89f9af-991b-4c9b-88d2-d7eef7060897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d40ce434-dcd3-4f76-867d-fc3b871776ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;Layout__Styles-sc-d7vu2k-0 fGSPvF&quot;]/div[@class=&quot;mt-3 container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-7 col-12&quot;]/form[1]/div[1]/div[@class=&quot;mt-5&quot;]/div[@class=&quot;FlightDetailForm__Styles-sc-zquz6k-1 fysaWR&quot;]/div[@class=&quot;shadow mb-3  card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;mb-3&quot;]/div[@class=&quot;SingleDatePicker__Styles-sc-1nrwzub-0 gBJcxo&quot;]/div[@class=&quot;day-picker-display-top&quot;]/div[@class=&quot;rdp&quot;]/div[@class=&quot;rdp-months&quot;]/div[@class=&quot;rdp-month rdp-caption_start rdp-caption_end&quot;]/div[@class=&quot;rdp-caption&quot;]/div[@class=&quot;rdp-nav&quot;]/button[@class=&quot;rdp-button_reset rdp-button rdp-nav_button rdp-nav_button_next&quot;]</value>
      <webElementGuid>ea008288-7144-44de-9895-d13e2c708ad0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='next-month']</value>
      <webElementGuid>5d4d841f-8eaa-48a4-a28d-9865c7063b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div[2]/div/form/div/div/div/div/div/div[3]/div/div/div/div/div/div/div[2]/button[2]</value>
      <webElementGuid>57c2bb18-a222-4a6e-ad14-95a2ea80a153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='November 2023'])[1]/following::button[2]</value>
      <webElementGuid>a36bd14f-c2db-4e58-ac84-a6621f7089e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flight Date'])[1]/following::button[2]</value>
      <webElementGuid>9c8eb2bb-c9b8-4481-87cc-ef18c57a8e57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[1]/preceding::button[1]</value>
      <webElementGuid>a37a3315-d6f2-4824-89a1-beb24a376991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mo'])[1]/preceding::button[1]</value>
      <webElementGuid>6f9f8de1-0f08-4483-a0cb-f6cecc30dd58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>c4d18995-2107-40f5-b9dd-382221fa0bb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'next-month' and @type = 'button']</value>
      <webElementGuid>1f1d5f0c-fbb1-4611-8de1-27cda8926ad6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
