<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_AddonAdventurousActivities</name>
   <tag></tag>
   <elementGuidId>f2a4b9f6-8479-4d7a-b806-3c1bd7c609af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add-on-coverage-input-adventurous-activities</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='add-on-coverage-input-adventurous-activities']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96fc5e94-f3e9-4aae-9815-4c8e347f4437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addonAdventurousActivities</value>
      <webElementGuid>9b9aa0f9-e254-4b6a-824c-a3f3b02edc58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c31fd650-e551-4865-a267-d6df1aff2342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-on-coverage-input-adventurous-activities</value>
      <webElementGuid>5513aee2-adbe-4463-a6f0-5129bfb53b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>2209f20f-eae3-4cff-97f6-690c0f2ec6cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-on-coverage-input-adventurous-activities&quot;)</value>
      <webElementGuid>4cfe9548-7103-44eb-abe9-9ee3725e4f00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='add-on-coverage-input-adventurous-activities']</value>
      <webElementGuid>4542e86c-a52a-4c99-b979-01722199fa52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div[2]/div/div[6]/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>e20d75a5-0e76-45b6-b535-9b1b56109f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>972108a8-4563-43d6-94e0-913642ef30a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'addonAdventurousActivities' and @type = 'checkbox' and @id = 'add-on-coverage-input-adventurous-activities']</value>
      <webElementGuid>56bc05ad-b141-48c7-a8d7-56de9b4d8a96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
