<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_EditPolicyOwner</name>
   <tag></tag>
   <elementGuidId>76f21039-2f1c-4880-b92e-16e1a07e84dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '#editAdult' and (text() = 'EDIT' or . = 'EDIT')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.PersonalDetailCard__StyledAnchor-sc-mpxnje-0.jcCzkJ.a-link-none-line</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div[2]/div/div[2]/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ed2a9dbf-ba5c-4592-a2ce-3c4fb3c01a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PersonalDetailCard__StyledAnchor-sc-mpxnje-0 jcCzkJ a-link-none-line</value>
      <webElementGuid>06d72736-6bde-496d-b9ec-b7fc9c16e10c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#editAdult</value>
      <webElementGuid>ab6e413a-cb84-4595-92c9-6a7604ac2d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EDIT</value>
      <webElementGuid>571d672f-8162-4f4d-be90-512b8bef479a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;Layout__Styles-sc-d7vu2k-0 fGSPvF&quot;]/div[@class=&quot;mt-3 container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-7 col-12&quot;]/div[@class=&quot;mb-3 shadow  card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;PersonalDetailCard__Styles-sc-mpxnje-2 vjxiN&quot;]/div[@class=&quot;card-title h5&quot;]/a[@class=&quot;PersonalDetailCard__StyledAnchor-sc-mpxnje-0 jcCzkJ a-link-none-line&quot;]</value>
      <webElementGuid>d50137d1-9e46-4cc7-b55e-eb6215d5a038</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div[2]/div/div[2]/div/div/div/a</value>
      <webElementGuid>94a17649-5c84-4ca2-89c0-f8bf197962a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'EDIT')]</value>
      <webElementGuid>3c043c5d-f43c-40f7-9a7f-11ad05d71f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment'])[1]/following::a[1]</value>
      <webElementGuid>2f49ee71-c263-4476-a58c-567f6907169b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal Details'])[1]/following::a[1]</value>
      <webElementGuid>4a580dda-461e-4e26-9274-0b76076c5892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::a[1]</value>
      <webElementGuid>2ed75413-09dd-47c6-af80-69d4a63587c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NRIC'])[1]/preceding::a[1]</value>
      <webElementGuid>7b652499-e95d-486b-beb2-0636a53d70e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='EDIT']/parent::*</value>
      <webElementGuid>991044c0-ba86-4afd-9ca2-d38ba4e65773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#editAdult')]</value>
      <webElementGuid>e149deea-e2de-4285-befb-00bebfc5b8cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>cfe487bf-5fe5-451e-a982-28a5700a8455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#editAdult' and (text() = 'EDIT' or . = 'EDIT')]</value>
      <webElementGuid>3b4f201a-4c37-46ac-8655-6af863f83359</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
