<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ReturnFlightDate</name>
   <tag></tag>
   <elementGuidId>7ad18a9e-d72b-4e19-9790-11236ea4738b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='return-flight-date-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#return-flight-date-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6afbdd9c-c543-443b-85fe-35a63ac67348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>returnFlightDate</value>
      <webElementGuid>c267710e-843c-46e5-8cab-fd3746c60072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>70fe096a-a4d2-4454-adeb-badf4c59ac6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>return-flight-date-input</value>
      <webElementGuid>6aa245ea-c51f-46a3-9f2c-93ff6ee833a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>092ebcbb-8bb7-412b-a806-f2644c19eb44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;return-flight-date-input&quot;)</value>
      <webElementGuid>a1e749dd-3798-40dd-972e-0a8e8ccc294e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='return-flight-date-input']</value>
      <webElementGuid>24bb5be1-539a-4ab2-9540-cf9d3ecf9f7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div[2]/div/form/div/div/div[2]/div/div/div[3]/div/input</value>
      <webElementGuid>da6567be-3284-4704-b2dd-ca0f86164504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/input</value>
      <webElementGuid>6a4c3da2-e3a0-40f1-9182-7a456f216260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'returnFlightDate' and @type = 'text' and @id = 'return-flight-date-input']</value>
      <webElementGuid>328246fd-2fb7-451e-af3f-b63fc300711f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
