<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CloseTravellerInformation</name>
   <tag></tag>
   <elementGuidId>3b00257d-9220-43e8-9ac8-5cb95e615ecf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.bi.bi-x-lg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=dialog >> a >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>809c284a-1b44-481e-bf8a-7a2685468d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-x-lg</value>
      <webElementGuid>085b2ffa-9dc8-4277-9f29-e83c5705c509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;fade modal show&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;my__Styles-sc-m72vn7-0 bcUoZd&quot;]/div[@class=&quot;border-bottom-0 modal-header&quot;]/a[@class=&quot;float-end text-secondary cursor-pointer&quot;]/i[@class=&quot;bi bi-x-lg&quot;]</value>
      <webElementGuid>4662fd82-1849-49c9-bb3e-248703a78b9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>aaa68130-7830-47a6-9e68-ca52f40ee759</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
