<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_EditPolicyOwner</name>
   <tag></tag>
   <elementGuidId>76f21039-2f1c-4880-b92e-16e1a07e84dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '#editAdult' and (text() = 'EDIT' or . = 'EDIT')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.PersonalDetailCard__StyledAnchor-sc-mpxnje-0.jcCzkJ.a-link-none-line</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@href='#editAdult'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>68fecd2f-1712-4757-92d4-0af71a3da246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PersonalDetailCard__StyledAnchor-sc-mpxnje-0 jcCzkJ a-link-none-line</value>
      <webElementGuid>642895ff-767d-44d1-a695-b06c946d83ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#editAdult</value>
      <webElementGuid>40b05060-f5eb-4dfc-b38e-70417bdf7cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EDIT</value>
      <webElementGuid>8571848e-027a-4af5-b924-6ba7fed32a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;Layout__Styles-sc-d7vu2k-0 fGSPvF&quot;]/div[@class=&quot;mt-3 container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-7 col-12&quot;]/div[@class=&quot;mb-3 shadow  card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;PersonalDetailCard__Styles-sc-mpxnje-2 vjxiN&quot;]/div[@class=&quot;card-title h5&quot;]/a[@class=&quot;PersonalDetailCard__StyledAnchor-sc-mpxnje-0 jcCzkJ a-link-none-line&quot;]</value>
      <webElementGuid>d05d18f5-b24c-4880-9c78-7f93926c4e70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div[2]/div/div[2]/div/div/div/a</value>
      <webElementGuid>ae06ea4e-bfed-4cd3-8b9f-61675bbe39e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'EDIT')]</value>
      <webElementGuid>c023be78-7eba-4d85-a11c-80881a569319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment'])[1]/following::a[1]</value>
      <webElementGuid>70bd785e-3100-4962-a833-a5b0e1c11ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal Details'])[1]/following::a[1]</value>
      <webElementGuid>f6f87432-dea3-4f16-bfbc-45d76fb46392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::a[1]</value>
      <webElementGuid>d457b2bf-e883-4550-a285-fc8cdac760d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NRIC'])[1]/preceding::a[1]</value>
      <webElementGuid>59be6f71-7325-4689-bd16-5602551142e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='EDIT']/parent::*</value>
      <webElementGuid>f08c518d-8f43-44ac-b521-ef6747e4d96a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#editAdult')]</value>
      <webElementGuid>0e75d9b6-90b2-4b57-8aa0-8ff78ef43a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>b0d2b588-84a7-4b01-aa7c-83a88b115412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#editAdult' and (text() = 'EDIT' or . = 'EDIT')]</value>
      <webElementGuid>46360993-1085-42de-a7bf-4e8481c2437c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
