<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_depart_flight_date</name>
   <tag></tag>
   <elementGuidId>55934a2b-bb8f-4551-9bda-f639fc6e26e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name = 'day' and @type = 'button' and (text() = '10' or . = '10')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;10&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8b5a7526-aef8-4a35-ba88-09c0bc5f70c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>day</value>
      <webElementGuid>55998a0c-2e58-44c0-a956-51797aa97b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rdp-day_today</value>
      <webElementGuid>c508fa48-17f2-4be4-baf3-a9818da3ab01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>fbcafda1-9674-4858-afb2-9c29c5245373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e56a4951-3722-49b2-a0fb-01d7c90c2b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2a51f052-4130-4ac6-b93b-429b4cfa1800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>5ced277a-5fab-48c8-a8b9-537649629cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;Layout__Styles-sc-d7vu2k-0 fGSPvF&quot;]/div[@class=&quot;mt-3 container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-7 col-12&quot;]/form[1]/div[1]/div[@class=&quot;mt-5&quot;]/div[@class=&quot;FlightDetailForm__Styles-sc-101dgzz-1 gORulL&quot;]/div[@class=&quot;shadow mb-3  card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;mb-3&quot;]/div[@class=&quot;SingleDatePicker__Styles-sc-1nrwzub-0 gBJcxo&quot;]/div[@class=&quot;day-picker-display-top&quot;]/div[@class=&quot;rdp&quot;]/div[@class=&quot;rdp-months&quot;]/div[@class=&quot;rdp-month rdp-caption_start rdp-caption_end&quot;]/table[@class=&quot;rdp-table&quot;]/tbody[@class=&quot;rdp-tbody&quot;]/tr[@class=&quot;rdp-row&quot;]/td[@class=&quot;rdp-cell&quot;]/button[@class=&quot;rdp-button_reset rdp-button rdp-day rdp-day_today&quot;]</value>
      <webElementGuid>4c8bf62a-1594-47d8-8766-81700b3df7eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@name='day'])[10]</value>
      <webElementGuid>9986481d-7c0a-4a68-8fa7-01e7a5355802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[3]/div/div[2]/div/form/div/div/div/div/div/div[3]/div/div/div/div/div/table/tbody/tr[2]/td[3]/button</value>
      <webElementGuid>015ef566-d665-4f37-b0a8-27ae2e361ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::button[10]</value>
      <webElementGuid>91791574-2e58-42f3-82e2-4e8fcacee885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::button[10]</value>
      <webElementGuid>5c87c4ef-bd09-42d4-8b3a-e27676b39e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return Flight'])[1]/preceding::button[22]</value>
      <webElementGuid>f9c2a436-ca02-40b3-b4e3-235895b3d82b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flight Number'])[2]/preceding::button[22]</value>
      <webElementGuid>1f0bed74-123d-4ac4-b83d-0bcc43f75748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='10']/parent::*</value>
      <webElementGuid>81d0cff5-158f-47a2-835f-ba6223c99efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/button</value>
      <webElementGuid>18f68885-f437-4bb7-a622-a842bf1e243a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'day' and @type = 'button' and (text() = '10' or . = '10')]</value>
      <webElementGuid>441f1c04-f21d-4790-a264-1d7de81eca5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
