<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_chkIsSameMailingAddress</name>
   <tag></tag>
   <elementGuidId>ec6f7fc0-1f1c-4264-bf0b-fb7bab6a0ccb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#custom-switch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='custom-switch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee8f9cd5-fa19-4112-86f3-2fa5ad4e4746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isSameMailingAddress</value>
      <webElementGuid>46e1f7fa-243b-47cb-ab9f-c76664c24518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>784fc01a-fc5f-4322-9201-0e0f7864da58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>custom-switch</value>
      <webElementGuid>94d9d528-473b-469e-8da3-5ff2cf73a310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>99fc3295-216e-41fa-b8ed-c771a75bb31f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom-switch&quot;)</value>
      <webElementGuid>1afae8b9-5c0a-40d5-8aa7-51f245059db4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='custom-switch']</value>
      <webElementGuid>07332e78-6f44-4d3f-8985-2b6654e899e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/input</value>
      <webElementGuid>797c1db0-15e4-4953-93dd-ccc9f164bcf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'isSameMailingAddress' and @type = 'checkbox' and @id = 'custom-switch']</value>
      <webElementGuid>20ae0bcf-ecf6-419f-b9c6-7497397b6370</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
