<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_DepartureFlightDate</name>
   <tag></tag>
   <elementGuidId>6809a3fc-6470-48e8-9aa7-0e3695048e0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='departure-flight-date-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#departure-flight-date-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f157003-e747-4d3d-bf2a-e551755904ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>departureFlightDate</value>
      <webElementGuid>9240000b-622e-41e4-aedd-3ee324adfe7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f23d3663-27a2-4f05-87d9-1d692f9db7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>departure-flight-date-input</value>
      <webElementGuid>c9169279-169f-4f73-9b7b-360377f05dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>941096bc-abdb-4998-9e95-d0c7f81c0518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;departure-flight-date-input&quot;)</value>
      <webElementGuid>192fd00f-cc77-4767-8218-6612fb76d5db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='departure-flight-date-input']</value>
      <webElementGuid>e13624fb-9978-463e-8e7d-aa7c122d75ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div[2]/div/form/div/div/div/div/div/div[3]/div/input</value>
      <webElementGuid>ca51b9af-6cc9-4855-9b8e-326507f2b685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>67a23283-e591-44b8-ada5-cb54fbf43e7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'departureFlightDate' and @type = 'text' and @id = 'departure-flight-date-input']</value>
      <webElementGuid>597ff372-a858-4d44-9d22-85aea8167c2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
