<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_AddonCovid19</name>
   <tag></tag>
   <elementGuidId>54141d0d-94dd-4cb1-9025-4ec100a2635d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add-on-coverage-input-covid-19</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='add-on-coverage-input-covid-19']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e764d70-7365-4b40-b339-a12333a1e149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addonCovid19</value>
      <webElementGuid>75d679ad-8830-47df-befb-726fbab437ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a06eac04-1157-4e5b-be84-0dfa69192717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-on-coverage-input-covid-19</value>
      <webElementGuid>10167722-62e3-42be-b45d-6e92541c87bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>f37ffa1c-65d8-41c7-a0b2-28767405dfa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-on-coverage-input-covid-19&quot;)</value>
      <webElementGuid>0833da51-59b6-4f62-949e-0b482368fac5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='add-on-coverage-input-covid-19']</value>
      <webElementGuid>29a28549-2056-4bbd-b253-55f16b0e0f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div[2]/div/div[6]/div/div/div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>35d021ed-1876-441a-a1d2-56ca52ed7291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>07d32055-576e-4299-a396-cb2674067d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'addonCovid19' and @type = 'checkbox' and @id = 'add-on-coverage-input-covid-19']</value>
      <webElementGuid>4863b171-39a6-4e27-b088-f187220c8846</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
