<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_Ethnicity</name>
   <tag></tag>
   <elementGuidId>8a588c23-3ade-4d19-9cb8-043ba2a073a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='personal-detail-form-input-ethnicity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#personal-detail-form-input-ethnicity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fd45769a-8ab4-4c88-83ba-cbefd85747f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ethnicity</value>
      <webElementGuid>aa5ef2e1-941b-4a7c-a2d8-e90a33eecfb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>bda8ccd7-4e7a-4174-bd5e-d5990117032e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personal-detail-form-input-ethnicity</value>
      <webElementGuid>689239e9-1ffc-4ae9-917e-6f147e4e09b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select Ethnicity--MalayChineseIndianOthers</value>
      <webElementGuid>599830d2-fb5a-4f13-b972-4a6ba58511c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal-detail-form-input-ethnicity&quot;)</value>
      <webElementGuid>04ae0049-b0a1-45ad-ac39-8b7cb0e03568</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='personal-detail-form-input-ethnicity']</value>
      <webElementGuid>fee507e2-7e68-4759-ae19-01fa893e4e04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ethnicity'])[1]/following::select[1]</value>
      <webElementGuid>0313b92d-a290-4c5c-9ba6-3adba3eefc90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Female'])[1]/following::select[1]</value>
      <webElementGuid>190364c7-a9a7-4514-a2fa-c62c11c0d5b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::select[1]</value>
      <webElementGuid>8629bce3-2355-4660-a2e4-89ef07200273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile Number'])[1]/preceding::select[1]</value>
      <webElementGuid>ca1d1339-836e-4d84-872b-065e2fe0f18c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>32931790-c8eb-46dc-b27c-c0ce5777abcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ethnicity' and @id = 'personal-detail-form-input-ethnicity' and (text() = '--Select Ethnicity--MalayChineseIndianOthers' or . = '--Select Ethnicity--MalayChineseIndianOthers')]</value>
      <webElementGuid>33393ad3-60f1-4832-a87b-5160e24fa7dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
