<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MobileNumber</name>
   <tag></tag>
   <elementGuidId>b2ad2fe1-8318-489c-b472-d808b2011095</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#personal-detail-form-input-mobile-number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='personal-detail-form-input-mobile-number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>578dd374-fdbd-4fba-a71d-1f1232f75658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mobileNumber</value>
      <webElementGuid>f8cb10b6-f5e5-44b8-b8bc-d26c5cd0f984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>cb49993f-0542-446d-a1ab-9c0e3ed845c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>95f7824b-af4e-47c3-87f4-48b97be6f875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>32ad3868-926c-4d69-8861-618af3d86868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personal-detail-form-input-mobile-number</value>
      <webElementGuid>bf45fd92-3ec5-416c-9dbc-60f5c3790a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a8e37079-9ba5-4d5e-9f99-9bf58c61293f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal-detail-form-input-mobile-number&quot;)</value>
      <webElementGuid>0cc17863-7709-4599-8887-09115de73ed9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='personal-detail-form-input-mobile-number']</value>
      <webElementGuid>8e062355-88d0-4d40-98ae-d7741a5ca002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/input</value>
      <webElementGuid>e34802a0-e375-4fcf-b007-1c372d564699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'mobileNumber' and @type = 'text' and @id = 'personal-detail-form-input-mobile-number']</value>
      <webElementGuid>6033b032-56d3-4e38-8213-6f9f82d7d8ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
