<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TravellerInfoEmail</name>
   <tag></tag>
   <elementGuidId>da20ff2a-dd3d-4263-91cf-73b05cd4528d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#personal-detail-form-input-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='personal-detail-form-input-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51d293b7-cccd-44bf-b09f-87e501edca86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>0ae5de4c-9054-4537-abc0-78d68d699464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>ba8edb3b-58fd-454b-bdf7-9c31e0935aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>02744921-709d-4150-a86e-96f7ba402a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personal-detail-form-input-email</value>
      <webElementGuid>c37165cb-e4ce-4d97-943d-d610709866d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a11591c8-7331-4e86-8bbd-0cae3766a85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal-detail-form-input-email&quot;)</value>
      <webElementGuid>5e549116-1ac9-46e4-98f6-3aee86497c76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='personal-detail-form-input-email']</value>
      <webElementGuid>62b02ff6-3896-493e-a8f7-06dcdefc9d62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>72c99cbe-3c4d-4e60-98be-ad717845ae3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'email' and @id = 'personal-detail-form-input-email']</value>
      <webElementGuid>6ef63ba3-b12f-4c85-905c-465218c6e725</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
