<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_This field is required(bank details)</name>
   <tag></tag>
   <elementGuidId>62118a4b-3bc5-480f-9222-2b337584b556</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'This field is required' or . = 'This field is required')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div[2]/div/form/div[2]/div/div/div/div[2]/div[3]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>366892ad-7ac7-4b43-bfe0-ef447f03811f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-danger</value>
      <webElementGuid>f980062f-573e-461b-a0d3-5e26603d5299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This field is required</value>
      <webElementGuid>79a7a94d-cf4d-414e-a6e4-c1ab30ef99cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;Layout__Styles-sc-d7vu2k-0 fGSPvF&quot;]/div[@class=&quot;mt-3 container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-7 col-12&quot;]/form[1]/div[2]/div[@class=&quot;mt-5&quot;]/div[@class=&quot;shadow mb-3 card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;BankAccountDetail__Styles-sc-14z4pi0-3 NFtGR&quot;]/div[@class=&quot;mb-3&quot;]/p[@class=&quot;text-danger&quot;]</value>
      <webElementGuid>c9408ff6-3a72-4a49-9546-67c8e4d712a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div[2]/div/form/div[2]/div/div/div/div[2]/div[3]/p</value>
      <webElementGuid>16b3b29c-ad10-4e9e-b43e-ee07204d58ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Account No.'])[1]/following::p[1]</value>
      <webElementGuid>5781f7b2-52c7-4020-a94a-4329c4dd3bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Bank'])[1]/following::p[2]</value>
      <webElementGuid>a4ad6c91-56af-4847-a7fc-a206f27bd775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adventurous Activities'])[1]/preceding::p[3]</value>
      <webElementGuid>2115c4c2-2848-4f96-b4f5-e41f4dc563a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p</value>
      <webElementGuid>5e57a8b3-d574-440a-a094-b287ebc8bd47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'This field is required' or . = 'This field is required')]</value>
      <webElementGuid>9ce48dc1-ec84-4a49-a859-3cfe193a8650</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
