<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_adventurous summary</name>
   <tag></tag>
   <elementGuidId>1a01ec12-a6cc-4e18-8918-050c464f61a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div[3]/div/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>47add7d0-2bbd-4724-87f3-85145997b189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-2 d-flex justify-content-between</value>
      <webElementGuid>33efa236-f1b8-4efa-9b49-1d9bca7531bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Adventurous ActivitiesRM18.50</value>
      <webElementGuid>b6046f04-5762-4585-aff1-7ee9c967e5ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;Layout__Styles-sc-d7vu2k-0 fGSPvF&quot;]/div[@class=&quot;mt-3 container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-5 col-12&quot;]/div[@class=&quot;PlanSummary__Wrapper-sc-shogl8-0 iYtQIk&quot;]/div[@class=&quot;PlanSummary__Styles-sc-shogl8-2 jdqkeg&quot;]/div[@class=&quot;rounded accordion&quot;]/div[@class=&quot;accordion-item&quot;]/div[@class=&quot;accordion-collapse collapse show&quot;]/div[@class=&quot;accordion-body&quot;]/div[@class=&quot;mb-2 d-flex justify-content-between&quot;]</value>
      <webElementGuid>2de3b932-3159-48e3-9eb4-c10cefaed8be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div[2]/div[2]/div/div/div/div[2]/div/div/div[2]</value>
      <webElementGuid>43f2f517-a911-416c-b624-44fba1e246b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RM67.50'])[1]/following::div[1]</value>
      <webElementGuid>4d348bd7-aaa6-4074-9210-344bf7ab3ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gross Premium'])[1]/following::div[1]</value>
      <webElementGuid>d6a653c9-cd4f-44ac-9668-499c1eb8a6a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div[2]/div/div/div[2]</value>
      <webElementGuid>12c689a7-dc6d-47e3-867f-0bba45be1449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Adventurous ActivitiesRM18.50' or . = 'Adventurous ActivitiesRM18.50')]</value>
      <webElementGuid>cced9d03-311d-48c9-b472-f5ccaef3422a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
