<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_PassportOrIdentityNumber</name>
   <tag></tag>
   <elementGuidId>ddc5e41a-e035-43ba-a80f-087466f47c93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='personal-detail-form-input-nric-or-passport']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#personal-detail-form-input-nric-or-passport</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27888db7-c836-4ec4-b5fc-23b91e27a5ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>identityNumber</value>
      <webElementGuid>ba3930b8-a102-44c9-91d4-e9ab5754af92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ab14cdb9-8259-4fbe-848b-1db784729be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>426af8ff-231b-4a8d-81a1-44a9b40971e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personal-detail-form-input-nric-or-passport</value>
      <webElementGuid>9ad6e124-3815-4332-b47f-29da8d019181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>02f1bcaa-432f-41e4-91e0-594e1eca2a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal-detail-form-input-nric-or-passport&quot;)</value>
      <webElementGuid>d6a0caa9-a8e5-4cd2-b84b-2f673afcb3fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='personal-detail-form-input-nric-or-passport']</value>
      <webElementGuid>b0d0c7b1-78ee-4b6e-8610-a9044995434e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/input</value>
      <webElementGuid>a3c6f6d5-fecf-4e4b-8cfe-2e12e257ccde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'identityNumber' and @id = 'personal-detail-form-input-nric-or-passport']</value>
      <webElementGuid>5f4a9841-470b-401c-aaa7-5fa5c66c2fa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
