<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtBankAccountNumber</name>
   <tag></tag>
   <elementGuidId>b6ea3a5f-ecdd-4ca1-bf87-c872850df56d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bank-account-number-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bank-account-number-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10c502a7-a9c9-4e1c-a48e-70ef2320dc8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bankAccountNumber</value>
      <webElementGuid>b411acb7-340b-4e63-9734-0a8706947342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2c2f4598-421c-498f-9cfe-b8da1bc4117a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bank-account-number-input</value>
      <webElementGuid>caee2355-090d-49e6-b4d3-6739e8de5fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9c0b296b-5cae-4e91-9794-f5b1894a22b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bank-account-number-input&quot;)</value>
      <webElementGuid>e6424322-ff95-4db8-92fd-ca4857b1c2d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bank-account-number-input']</value>
      <webElementGuid>2149d19f-847e-4893-83fa-a44c9f917847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div[2]/div/form/div[2]/div/div/div/div[2]/div[3]/input</value>
      <webElementGuid>969f36af-3d29-4d4f-aa0a-90bad52375ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>b8eda7a9-de95-4a89-9e4b-f01711f2ceb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'bankAccountNumber' and @type = 'text' and @id = 'bank-account-number-input']</value>
      <webElementGuid>493870ee-7376-4022-90c1-d12877702d98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
