<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtDepartureFlightNumber</name>
   <tag></tag>
   <elementGuidId>774c1041-67e7-4f67-bcf7-1f9d08dd368a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#departure-flight-number-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='departure-flight-number-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dcdd5815-93c3-4dd5-871b-ef92e5380beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>departureFlightNumber</value>
      <webElementGuid>840f95ba-7993-4048-aae5-a1265f659c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5df184f3-fc8e-4470-96ec-7275b768ae52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>departure-flight-number-input</value>
      <webElementGuid>27c78372-a931-43b4-9dc1-a3efae3b7911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>975fabf8-c2a3-4a94-bcf6-a6242f02df5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;departure-flight-number-input&quot;)</value>
      <webElementGuid>2142504b-6051-4c5b-8f77-fd00fe052bb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='departure-flight-number-input']</value>
      <webElementGuid>a23d7cb3-7435-48e9-9b73-de0c9f542297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div[2]/div/form/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>b4cfc219-1b1b-4d3a-823f-17961c12a4ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>85a2c58c-f987-4726-a944-b7c369bf3443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'departureFlightNumber' and @type = 'text' and @id = 'departure-flight-number-input']</value>
      <webElementGuid>7b873c69-3a58-4de4-a947-6ea03f8bf434</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
