<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close Motorcycle Details</name>
   <tag></tag>
   <elementGuidId>1eab29a9-8675-4fd3-867d-6f9dd916eb69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[contains(@class,'VehicleDetailsForm__Buttons-sc-sfhf3o-1')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>4f85fa9c-58b3-4de1-b8ea-1eb43be7a8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1735550556336</value>
      <webElementGuid>d65a8975-c317-43f4-bbd1-97472fc1e05d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
