<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save Motorcycle Details</name>
   <tag></tag>
   <elementGuidId>23723dc2-6156-4a2b-b922-811d37ed4b53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[contains(@class,'VehicleDetailsForm__Buttons-sc-sfhf3o-1')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>a1ae7dac-9185-4cdd-88a0-20fa15dbd326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1735549802611</value>
      <webElementGuid>fdce9269-3b01-419f-8755-0754e94983b3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
