<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ContentsSumInsured</name>
   <tag></tag>
   <elementGuidId>cb90569b-a2e3-46e7-b2f1-bc723639a63d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='contentSumInsured']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;contentSumInsured&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;contentSumInsured&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3722adc9-5f46-4226-bcd8-ad0adb5d33c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>fb4396f7-59c1-487e-85fb-d5229f8c30f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contentSumInsured</value>
      <webElementGuid>a0f5ca55-396d-4cc9-bf1a-7a1d706f8ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f3482e2c-d549-4792-aa81-1432fb3fc665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AmountInput__FormControl-sc-xyqav3-0 iFmBta form-control</value>
      <webElementGuid>d8c3c3a5-8c4c-406b-9de5-50e2808fd054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;layout__Styles-sc-wetbic-0 ehlvJr&quot;]/div[@class=&quot;plan__Styles-sc-1bba8d0-0 dlSxDC bg-white&quot;]/form[1]/div[@class=&quot;container-padding-hide container&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;d-grid gap-3 my-4&quot;]/div[@class=&quot;justify-content-md-center gap-3 row&quot;]/div[@class=&quot;plan__CardStyle-sc-1bba8d0-1 iAjANn bg-yellow card&quot;]/div[@class=&quot;d-flex justify-content-between gap-1 false&quot;]/div[@class=&quot;amount-input&quot;]/div[@class=&quot;AmountInput__FormGroup-sc-xyqav3-1 fzkICv&quot;]/div[@class=&quot;undefined undefined input-group&quot;]/input[@class=&quot;AmountInput__FormControl-sc-xyqav3-0 iFmBta form-control&quot;]</value>
      <webElementGuid>9848d64c-fc87-453d-b82d-96ed47b28733</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='contentSumInsured']</value>
      <webElementGuid>4a0ce5ee-47b2-4dfc-8468-6ea11c096796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/form/div/div[2]/div/div[4]/div/div/div[2]/div/div/input</value>
      <webElementGuid>00e097ac-47ba-496a-a016-05301bc3b7f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div/input</value>
      <webElementGuid>8971bf68-ef21-4191-a133-d2077a176afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'contentSumInsured' and @type = 'text']</value>
      <webElementGuid>1c41dd59-8562-4fda-ac71-1c16c75aa52d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
