<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_MarketingConsent</name>
   <tag></tag>
   <elementGuidId>06a5c9c3-79bb-4326-9491-ac5f3b287377</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#marketing-consent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='marketing-consent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#marketing-consent</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>baec7d02-c203-4a74-8b6f-456cbdccd624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>marketingConsent</value>
      <webElementGuid>e20452db-d728-4c7c-8bba-b6db752c5688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a3dc822d-23e4-4624-bf61-517066fc1032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>marketing-consent</value>
      <webElementGuid>54e56f20-98c1-4218-a73c-7614376618d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>103cc1ed-ce17-409f-9bf8-179bcfafd7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;marketing-consent&quot;)</value>
      <webElementGuid>4b4cf028-3c3d-4eb8-8085-eb8f4ac17205</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='marketing-consent']</value>
      <webElementGuid>01eae888-0cee-4fc7-8feb-648828c43c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/form/div/div/div[3]/div/div[2]/div/div[2]/div/div/div[2]/div/div/input</value>
      <webElementGuid>309bb652-cf82-44c0-84e4-6a3b3de40783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div[2]/div/div/input</value>
      <webElementGuid>bf49b006-e040-4d70-b6d9-f21afe4bcb79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'marketingConsent' and @type = 'checkbox' and @id = 'marketing-consent']</value>
      <webElementGuid>fc9c6410-dab5-4504-ae49-bffb42893382</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
