<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_FPX</name>
   <tag></tag>
   <elementGuidId>2cd99fbd-86ec-4e33-8894-a44dce46dd54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='data' and @value='FPX']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Online Banking$/ >> internal:role=radio</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e9e20d7-5cbb-49bc-8fcf-c9f8c4e201de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data</value>
      <webElementGuid>3a894914-92d8-4c55-abfc-b0722f4d62aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>90e0989f-6460-49bc-aa41-a3e8d2fe454d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>e05282b9-c95a-4b56-aac3-8efa0643f449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>FPX</value>
      <webElementGuid>75d91f93-2d99-4e52-a0f4-07ebb46cdad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;layout__Styles-sc-wetbic-0 ehlvJr&quot;]/div[@class=&quot;review__Styles-sc-1phfw32-0 kSPXQV&quot;]/form[1]/div[@class=&quot;mb-3 container-padding-hide container&quot;]/div[@class=&quot;gy-3 gx-5 row&quot;]/div[@class=&quot;col-lg-7 col-md-6 col-12&quot;]/div[@class=&quot;g-3 gap-3 row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;d-flex flex-column gap-3&quot;]/div[@class=&quot;PayModeForm__Styles-sc-1v31h5r-0 cERqDK&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[1]/div[@class=&quot;ImageRadioButton__FormCheck-sc-15fkqpn-0 fAlyzR form-check&quot;]/input[@class=&quot;form-check-input&quot;]</value>
      <webElementGuid>fe641404-b5d1-4117-8fd1-0bb75759bf1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='data'])[3]</value>
      <webElementGuid>74d514b9-1da6-438e-95fe-4b19a2c9fcaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/form/div/div/div[3]/div/div[3]/div/div[2]/div/div/div/div[3]/input</value>
      <webElementGuid>03349115-3ac2-4781-833d-41f26407c928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>27110cc4-d8a7-4026-b759-3fd25f04efd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'data' and @type = 'radio']</value>
      <webElementGuid>bf61f978-c38f-4966-a6dc-91ba1d6f98bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
