<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Declaration</name>
   <tag></tag>
   <elementGuidId>cc00eb4d-ba76-4432-9913-a83a2d5953ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#declaration</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='declaration']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#declaration</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>260baebc-0096-4ff3-a66d-a63ccf9e27f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>declaration</value>
      <webElementGuid>02373f05-fd2f-4638-8e39-5ad752defb7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b64da1c9-c0fc-4a33-ab9b-f3a38b78b8a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>declaration</value>
      <webElementGuid>b697e8f5-a9cd-41ba-9d87-fc2138b1a95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>f7f2274e-8f8d-4363-83bc-dbf2e407d03e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;declaration&quot;)</value>
      <webElementGuid>b7c1b98b-6371-4c97-ab3d-3603f9d84b1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='declaration']</value>
      <webElementGuid>47e423f6-fdea-4ece-bf64-3ed345670f23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/form/div/div/div[3]/div/div/div/div[2]/div/div/div[2]/div/div/input</value>
      <webElementGuid>c8ec5b39-5dbf-4d38-b0f7-dcb313ff8c7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5c17e275-85b5-4575-8cc3-619ebcd1dbfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'declaration' and @type = 'checkbox' and @id = 'declaration']</value>
      <webElementGuid>1137aae7-b6e8-43a7-9383-1de5c66b9747</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
