<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Visa,MasterCards</name>
   <tag></tag>
   <elementGuidId>db59392c-1d76-4f7a-9f34-2c2a89648564</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='data' and @value='CARD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Visa/Master Cards$/ >> internal:role=radio</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a0bd7b2-1df7-458e-8259-ea9d0b794fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data</value>
      <webElementGuid>ff49cfca-ac64-4746-bacd-73bfde0db6a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0d72b45d-92a7-463e-ae79-cca414cd38c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>e4525ee5-fd4e-49a1-a3bf-e51d7f4a4cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>CARD</value>
      <webElementGuid>84ef4fb2-f342-4de8-8729-beb19036adb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;layout__Styles-sc-wetbic-0 ehlvJr&quot;]/div[@class=&quot;review__Styles-sc-1phfw32-0 kSPXQV&quot;]/form[1]/div[@class=&quot;mb-3 container-padding-hide container&quot;]/div[@class=&quot;gy-3 gx-5 row&quot;]/div[@class=&quot;col-lg-7 col-md-6 col-12&quot;]/div[@class=&quot;g-3 gap-3 row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;d-flex flex-column gap-3&quot;]/div[@class=&quot;PayModeForm__Styles-sc-1v31h5r-0 cERqDK&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[1]/div[@class=&quot;ImageRadioButton__FormCheck-sc-15fkqpn-0 fAlyzR form-check&quot;]/input[@class=&quot;form-check-input&quot;]</value>
      <webElementGuid>7be42f98-35e3-40e8-9cbb-9cbf4fbe59a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='data'])[2]</value>
      <webElementGuid>823207c8-301c-4750-9ff8-136be6e9d0b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/form/div/div/div[3]/div/div[3]/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>73cf4ac5-e9d3-4484-972e-92d51e903fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>cd9ba770-56e3-4420-ab56-78430dae8768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'data' and @type = 'radio']</value>
      <webElementGuid>9349284e-6962-4b2c-9875-b0dd48a0e0a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
