<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_AmericanExpress</name>
   <tag></tag>
   <elementGuidId>9317b698-24e3-4e5d-b240-152e6204b3d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;data&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='data' and @value='AMEX']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^American Express$/ >> internal:role=radio</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a9e2314-d65c-426f-a8dd-83a5eacef327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data</value>
      <webElementGuid>a818ddd7-5dc6-439f-bf61-0b7e6735d67d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>90f1dce7-3928-4901-86a8-bacba739175c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>50763e43-e3c2-45a1-a442-c363e31b7b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>AMEX</value>
      <webElementGuid>783e4089-1200-43b8-b903-aba2766322a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;layout__Styles-sc-wetbic-0 ehlvJr&quot;]/div[@class=&quot;review__Styles-sc-1phfw32-0 kSPXQV&quot;]/form[1]/div[@class=&quot;mb-3 container-padding-hide container&quot;]/div[@class=&quot;gy-3 gx-5 row&quot;]/div[@class=&quot;col-lg-7 col-md-6 col-12&quot;]/div[@class=&quot;g-3 gap-3 row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;d-flex flex-column gap-3&quot;]/div[@class=&quot;PayModeForm__Styles-sc-1v31h5r-0 cERqDK&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[1]/div[@class=&quot;ImageRadioButton__FormCheck-sc-15fkqpn-0 fAlyzR form-check&quot;]/input[@class=&quot;form-check-input&quot;]</value>
      <webElementGuid>27f5dac8-9ba8-4935-848b-4ecede4c8bc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='data']</value>
      <webElementGuid>efc80cbf-52c1-42b4-b52e-8c525992fba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/form/div/div/div[3]/div/div[3]/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>583525eb-92b5-4abc-974c-3868ccde4143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>d79ecaed-4fac-42e8-88a0-84acf9d4d540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'data' and @type = 'radio']</value>
      <webElementGuid>3af23f78-999d-49c9-9e09-8e07f119dec3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
