<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_ProductDisclosureSheet</name>
   <tag></tag>
   <elementGuidId>56e8e36e-68d8-4441-b50f-19deec5da80e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@aria-label='disclosure-sheet']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>b8139157-2337-4122-9c65-d8fb3d190027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1736413112598</value>
      <webElementGuid>f7487a58-02c0-4872-a302-1f53f8b40d4d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
