<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_PIDMTIPSBrochure</name>
   <tag></tag>
   <elementGuidId>cdabcfc6-12c0-47d9-b5fb-d81a5a617d97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'TIPS Brochure')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>caed52db-1b2d-402a-a23b-8228aa0053c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1736413797796</value>
      <webElementGuid>fdcc0aa5-6d43-4fee-9ec1-387a24035f4c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
