<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Loss or damage to baggage, personal _04c44b</name>
   <tag></tag>
   <elementGuidId>15663072-d2ed-40c1-83f6-15669b79cd20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.accordion-button.collapsed</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Loss or damage to baggage, personal belongings, personal money and/or travel documents&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fd334652-2485-447e-b67d-500a0cbd4cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>196daf43-9fc2-4387-a073-f8e3636736e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a561cd72-5914-46e5-9e8c-91b95655c29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion-button collapsed</value>
      <webElementGuid>6ab4456f-f3a4-4a89-8cbd-e10dbbc3ba75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Loss or damage to baggage, personal belongings, personal money and/or travel documents</value>
      <webElementGuid>3f318529-ed1d-4ffc-9160-f6924e4522d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;Layout__Styles-sc-d7vu2k-0 fGSPvF&quot;]/div[@class=&quot;mt-3 container&quot;]/div[@class=&quot;ItemLossOrDamage__Styles-sc-xu6dlr-0 ktQTML&quot;]/div[@class=&quot;mb-5 accordion&quot;]/div[@class=&quot;border-0 accordion-item&quot;]/h2[@class=&quot;bg-secondary text-white shadow-none accordion-header&quot;]/button[@class=&quot;accordion-button collapsed&quot;]</value>
      <webElementGuid>a8a851c0-8cbd-4569-a284-98094cba9324</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>abea6153-ebaa-49cf-9f77-fd8fc2d02538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[3]/div/div[10]/div/div/h2/button</value>
      <webElementGuid>731c76ed-5021-40f9-a53b-849a5d9876f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Maximum of RM1,500 per family*)'])[1]/following::button[1]</value>
      <webElementGuid>301fd624-47ff-475d-ab10-0019527f16f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RM600'])[2]/following::button[1]</value>
      <webElementGuid>bcd566b1-fcd7-4e95-82c4-7a67ae8383a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Losses or Damages to Baggage and/or Personal Effects (combined limit, up to)'])[1]/preceding::button[1]</value>
      <webElementGuid>50be9d67-1230-48d6-b648-147850e69f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RM1,000'])[5]/preceding::button[1]</value>
      <webElementGuid>8670b95b-9fe3-481d-a03b-5ecdcf9a106a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Loss or damage to baggage, personal belongings, personal money and/or travel documents']/parent::*</value>
      <webElementGuid>d02c0f61-f5fe-44b6-9689-ef5572bd5c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/h2/button</value>
      <webElementGuid>890b1be4-2785-4437-b6ff-ba3f6686c767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Loss or damage to baggage, personal belongings, personal money and/or travel documents' or . = 'Loss or damage to baggage, personal belongings, personal money and/or travel documents')]</value>
      <webElementGuid>2a62124f-87fb-4961-8e9d-9e00438e1304</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
