<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CovidAddOn</name>
   <tag></tag>
   <elementGuidId>7a04a324-0a63-4a8f-904c-453eaaa538b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='covidAddon']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'covidAddon' and @type = 'checkbox' and @id = 'covidAddon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#covidAddon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b17df0d-27d7-4677-bfe6-460ce3bd8327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>covidAddon</value>
      <webElementGuid>6bd51e51-4566-42d1-88ca-fcd5cc6464b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>58731858-1979-4236-8eec-ef5ac182f47c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>covidAddon</value>
      <webElementGuid>8fca56c8-4421-46f7-ba5c-34af8386a4b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>a053e986-9744-4e56-8497-e54bbd22a522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;covidAddon&quot;)</value>
      <webElementGuid>ab5bed27-86be-48af-af9a-5c4d200f54b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='covidAddon']</value>
      <webElementGuid>3ea8b195-788e-4223-888a-5a9b031ec910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[3]/div/div[15]/div/div/div/div/h2/button/div/div/div/input</value>
      <webElementGuid>0055ad6a-e086-4311-afb0-77b8c3387c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div/div/input</value>
      <webElementGuid>db4887d1-d616-4c25-b02a-29be74b818cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'covidAddon' and @type = 'checkbox' and @id = 'covidAddon']</value>
      <webElementGuid>1f9ad86a-a5cf-45ab-89a5-8470e19c071d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
