<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>submit_Buy</name>
   <tag></tag>
   <elementGuidId>2b8cefa3-eaf5-4ebc-91f1-af802d041d85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[12]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = 'Buy' or . = 'Buy')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ButtonStepper__ButtonDiv-sc-1p030oz-0.hxyfdW.px-5.py-2.float-end.btn.btn-warning.btn-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4df9c1cd-8d3d-4abd-89dc-98cd166c9e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0064699a-376c-4e99-a5dc-50687583d331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ButtonStepper__ButtonDiv-sc-1p030oz-0 hxyfdW px-5 py-2 float-end btn btn-warning btn-sm</value>
      <webElementGuid>2578c496-09e7-4fab-bcca-5a061d287402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buy</value>
      <webElementGuid>7ed6b600-3f95-4327-8afb-fe96710e64f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;Layout__Styles-sc-d7vu2k-0 fGSPvF&quot;]/div[@class=&quot;ButtonStepper__Wrapper-sc-1p030oz-1 hZrHDM&quot;]/div[@class=&quot;ButtonStepper__TransparentWrapper-sc-1p030oz-2 eUFNlx&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;my-3 row&quot;]/div[@class=&quot;p-0&quot;]/button[@class=&quot;ButtonStepper__ButtonDiv-sc-1p030oz-0 hxyfdW px-5 py-2 float-end btn btn-warning btn-sm&quot;]</value>
      <webElementGuid>002bb565-42aa-4530-bf27-58e6554c7935</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[12]</value>
      <webElementGuid>3bfd93d6-f5f2-4077-ad70-c43c67c1a705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div[2]/div/div/div/div/button[2]</value>
      <webElementGuid>d02c3071-66ac-4dc7-ba7c-e8fda9ae7898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::button[1]</value>
      <webElementGuid>9f5c97ad-b0be-4726-be3c-752e7cf44a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RM1,500,000'])[2]/following::button[2]</value>
      <webElementGuid>e4ce44e7-8214-4004-b529-bddd7fe9a178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Navigated to Plan Selection'])[1]/preceding::button[1]</value>
      <webElementGuid>7c98f53b-1306-436d-ac9e-6fe702ed09bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[1]</value>
      <webElementGuid>7a45e500-454e-4ff4-8faf-cde8a5f3e1d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buy']/parent::*</value>
      <webElementGuid>00aa66d3-41d7-4966-985a-ea5dc3494bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>f9d00a3d-1113-4f92-9b08-a08b9df5894a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Buy' or . = 'Buy')]</value>
      <webElementGuid>ad61a0ef-b753-4a6f-835f-2d34e350f77b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
