<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_silverPlan</name>
   <tag></tag>
   <elementGuidId>5c70abe2-2df2-4172-9bef-eaf454242512</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='plan-type-silver']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#plan-type-silver</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;SilverRM 121.00 / yearAccidental Death RM 10,000Accidental Permanent Disability (up to) RM 10,000Double Indemnity up to RM 20,000Medical Expenses up to RM 500Hospital Income RM 50 per dayCompassionate cash RM 1,000Facial reconstructive surgery and/or dental treatment up to RM 1,000&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64dcd196-3aff-4949-80b5-83b9753fc6f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>planTypee</value>
      <webElementGuid>8ae67678-3130-4660-8ad2-25dfdd9f0882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4a5952a1-bedb-4e7f-a2bb-39bac0cb1124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>plan-type-silver</value>
      <webElementGuid>77f3ada9-e350-410d-9342-e213cb6fa3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>f1617c5b-58bb-4a91-93c4-bc993da27e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9d4f239d-6ca0-47e8-9e4b-5f5e09065ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;plan-type-silver&quot;)</value>
      <webElementGuid>b560003a-bd22-4139-89bb-36063ab826f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='plan-type-silver']</value>
      <webElementGuid>4849b9f3-1304-4fd8-af6b-10f2d53278ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/form/div/div[2]/div/div/div/div/label/div/div/div/input</value>
      <webElementGuid>604f521d-2eda-421d-851a-4a24b5484efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d7f1857f-469a-459f-a475-88dbbf2e1d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'planTypee' and @type = 'checkbox' and @id = 'plan-type-silver']</value>
      <webElementGuid>927ac167-2de9-4e90-a707-1bc64f97e19e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
