<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_goldPlan</name>
   <tag></tag>
   <elementGuidId>8f9e8e9d-2c48-482a-a230-8cd5abaa9f01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='plan-type-gold']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#plan-type-gold</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;GoldRM 158.00 / yearAccidental Death RM 25,000Accidental Permanent Disability (up to) RM 25,000Double Indemnity up to RM 50,000Medical Expenses up to RM 500Hospital Income RM 50 per dayCompassionate cash RM 1,000Facial reconstructive surgery and/or dental treatment up to RM 1,000&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e890ba0-2cc0-481d-8e65-a47743bab371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>planTypee</value>
      <webElementGuid>59af728f-fa3d-472d-935b-41f35bfed1af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7eebd3ca-e5f5-4b85-9cb4-0a9af2c53de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>plan-type-gold</value>
      <webElementGuid>9eaefd4f-364d-400a-a956-523b48820030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>15088502-fe45-4227-aa04-7afc8a38bfe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5246157f-08d4-489d-9de5-6052d79dfb07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;plan-type-gold&quot;)</value>
      <webElementGuid>30e63a9c-cc41-4f80-8696-4bb5bf47df79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='plan-type-gold']</value>
      <webElementGuid>58c8a142-bc1a-4ff0-a36d-4140817b8895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/form/div/div[2]/div/div/div[2]/div/label/div/div/div/input</value>
      <webElementGuid>1a0a2c1a-25cb-4051-bad7-580c03343c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label/div/div/div/input</value>
      <webElementGuid>069f6e2d-48fd-4dbb-b77f-20baabd458f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'planTypee' and @type = 'checkbox' and @id = 'plan-type-gold']</value>
      <webElementGuid>90cbb5ec-91cc-4a00-a7a7-65d969374a2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
