<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_platinumPlan</name>
   <tag></tag>
   <elementGuidId>9f1fcc9e-3a2c-4c9d-915d-02cd83369e4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='plan-type-platinum']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#plan-type-platinum</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;PlatinumRM 201.00 / yearAccidental Death RM 50,000Accidental Permanent Disability (up to) RM 50,000Double Indemnity up to RM 100,000Medical Expenses up to RM 1,000Hospital Income RM 100 per dayCompassionate cash RM 1,000Facial reconstructive surgery and/or dental treatment up to RM 1,000&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>280d587c-8f70-448a-80c5-40c0088695a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>planTypee</value>
      <webElementGuid>1fe6f44c-4af3-4c86-8a4b-2aa68e2527dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>46a4a64e-6b11-405b-a10b-970d1d0a67bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>plan-type-platinum</value>
      <webElementGuid>d4133ae5-3a4b-4eeb-881e-cb9c6c7fed94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>09fc409d-4c47-43fc-86c4-3da206615c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>87732fbf-4baf-46b9-a284-d5102b1f1283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;plan-type-platinum&quot;)</value>
      <webElementGuid>85125b06-454c-432e-8b3c-8e39a46acbf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='plan-type-platinum']</value>
      <webElementGuid>dcf75dbd-db42-4b9c-b055-996fa955d019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/form/div/div[2]/div/div/div[3]/div/label/div/div/div/input</value>
      <webElementGuid>8f913d3b-f603-46b0-8fb4-faf5b769458f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/label/div/div/div/input</value>
      <webElementGuid>bb6d0590-66f3-4b3b-b284-74d040a42731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'planTypee' and @type = 'checkbox' and @id = 'plan-type-platinum']</value>
      <webElementGuid>67731925-ee93-4cde-89c8-39ef5a85a170</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
