<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_FPX</name>
   <tag></tag>
   <elementGuidId>a4f2d70e-289d-4d30-8d76-f42b92d9f90b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='FPX']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Online Banking$/ >> internal:role=radio</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2b6ef3d-a547-4dba-ada7-cc4d9326b05a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data</value>
      <webElementGuid>59ec2098-dcee-412a-8ea6-5a128cfe08ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>982b2416-9062-4746-94cb-ba64777139b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>7158fee4-a6bd-42b3-802e-90374ac010e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>FPX</value>
      <webElementGuid>67322bdc-c85a-4478-80bf-ea4b6dda3509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;layout__Styles-sc-csgnm7-0 iJzkTS&quot;]/div[@class=&quot;review__Styles-sc-2lqce7-0 fmaTwy&quot;]/form[1]/div[@class=&quot;container-padding-hide container&quot;]/div[@class=&quot;gy-3 gx-5 row&quot;]/div[@class=&quot;col-lg-7 col-md-6 col-12&quot;]/div[@class=&quot;g-3 gap-3 row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;d-flex flex-column gap-3&quot;]/div[@class=&quot;PayModeForm__Styles-sc-nvdk5j-0 kVeUgs&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[1]/div[@class=&quot;ImageRadioButton__FormCheck-sc-14clilz-0 nZlPi form-check&quot;]/input[@class=&quot;form-check-input&quot;]</value>
      <webElementGuid>12c553d6-2386-46b9-8f0b-dba44f532e39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='data'])[5]</value>
      <webElementGuid>c987d12e-7c0c-471b-b484-25defdd53a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/form/div/div/div[3]/div/div[3]/div/div[2]/div/div/div/div[5]/input</value>
      <webElementGuid>43955c61-1fa5-4a28-a0e0-0740dff34cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>1200a017-9840-40b2-a063-6c5d012eaee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'data' and @type = 'radio']</value>
      <webElementGuid>d7eee9d4-5798-4426-bd83-4b88d8b3aba2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
