<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_PIDMTIPSBrochure</name>
   <tag></tag>
   <elementGuidId>537068aa-48aa-4bc2-9c2e-986b55849acc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'TIPS Brochure')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>3d1b6006-4b43-4498-b613-f90f3a65d9c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1736413797796</value>
      <webElementGuid>3ee03f68-0939-47c6-bca3-048b2e706780</webElementGuid>
   </webElementProperties>
</WebElementEntity>
