<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Get Quote Now</name>
   <tag></tag>
   <elementGuidId>e1caf60f-be39-4e7e-8b21-d76907b0ee4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#get-quote-button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'get-quote-button' and (text() = 'Get Quote Now' or . = 'Get Quote Now')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='get-quote-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Get Quote Now&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f9c85123-e009-4641-8774-9602eb7fedbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>683e7e85-0071-4e1a-a775-4fa0f66831fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>get-quote-button</value>
      <webElementGuid>fdd8707a-d552-4829-9798-67b8d236394a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>get-quote-button btn btn-primary w-100 mb-3 btn btn-primary</value>
      <webElementGuid>e2e6ef3d-e5a9-43c0-b91e-c95b197a1f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get Quote Now</value>
      <webElementGuid>15bab8a3-6f24-4f16-b9af-3243781793d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;get-quote-button&quot;)</value>
      <webElementGuid>a1be7125-3159-454a-b717-9d4fd297a198</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='get-quote-button']</value>
      <webElementGuid>75369382-534f-444f-ad9e-d892feb69390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/div/div/div[2]/div/div/div[2]/div/form/button</value>
      <webElementGuid>12acdb59-4bab-496b-b3d7-246b6822202e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID Number'])[1]/following::button[1]</value>
      <webElementGuid>8427fe2d-799c-4615-9d73-82fbcb818d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NRIC Number'])[1]/following::button[1]</value>
      <webElementGuid>3cb50aa4-622c-4984-a3b9-73035fc44e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Average Customer Rating:'])[1]/preceding::button[1]</value>
      <webElementGuid>80b6b636-65a9-445c-934e-c61d5a37f342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get Quote Now']/parent::*</value>
      <webElementGuid>2c53341e-e763-4ab9-b8d1-23706210a50c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>7d88dc45-e418-4176-9616-a17aec1e33df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'get-quote-button' and (text() = 'Get Quote Now' or . = 'Get Quote Now')]</value>
      <webElementGuid>833c3647-aff3-426e-a197-18002311f9e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
