<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Postcode</name>
   <tag></tag>
   <elementGuidId>1df099f1-fb22-4d00-b80c-9ec9d1fc529a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vehicle-postcode</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@placeholder = 'EG : 51200' and @name = 'postcode' and @type = 'text' and @id = 'vehicle-postcode' and @class = 'textfield-height  form-control']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vehicle-postcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;EG : 51200&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>094eaa97-8f67-410c-9ec6-b46677bf773f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>EG : 51200</value>
      <webElementGuid>b5924aed-46fd-419a-99d1-059a491c37cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e2cde623-773c-4f10-bead-1026eadcee91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>c44c86e9-1710-4ee6-b729-8e03fc510f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>ab3321c7-fec2-4f2f-8105-88e2cd3c1089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>postcode</value>
      <webElementGuid>469beb66-87ae-4e08-ba19-0b9fe7e3ed67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a5480341-8a1a-46f3-b158-279021d41797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vehicle-postcode</value>
      <webElementGuid>d91375d6-6806-4973-9bf4-24a7fc977622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield-height  form-control</value>
      <webElementGuid>cc3b5ecf-6b52-4508-b480-201601607c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vehicle-postcode&quot;)</value>
      <webElementGuid>11f0c732-8e43-4451-9292-a7d8c1441186</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vehicle-postcode']</value>
      <webElementGuid>c1009d35-48ba-45fd-b52c-5c097283990f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/div/div/div[2]/div/div/div[2]/div/form/div[2]/input</value>
      <webElementGuid>3979abdd-6786-4e48-bac5-267cc635c698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>5647b47b-6de4-4529-a194-a6be453e394c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'EG : 51200' and @name = 'postcode' and @type = 'text' and @id = 'vehicle-postcode']</value>
      <webElementGuid>935bdfe2-7c13-416e-bd34-aa8e3f2657d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
