<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Passport</name>
   <tag></tag>
   <elementGuidId>cefaeeeb-5f4e-4bb5-a089-f2bae787fa63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id-number</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'govId' and @placeholder = 'EG : A12345678' and @type = 'text' and @id = 'id-number' and @class = 'textfield-height undefined form-control']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id-number']/preceding-sibling::label[text()='Passport']/following-sibling::input[@id='id-number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;EG : A12345678&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>705872eb-3ba2-4b33-b250-a0c9a9e84765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>07aba84a-4f79-4318-b22b-64ae61e5cbd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>a392ea9a-3372-4133-9209-8c9329f0ab33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>govId</value>
      <webElementGuid>dd70014b-c5e5-4f99-8514-f7b3f86142cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>EG : A12345678</value>
      <webElementGuid>24d39a9e-0d49-4bee-9fc2-7a26ecb3e00a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1fc09366-6eed-4561-aad6-9a562ee71a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-number</value>
      <webElementGuid>1716f7f1-19f8-4a85-8c7b-632c4c5f91db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield-height undefined form-control</value>
      <webElementGuid>3bc01900-46d5-424f-a456-5dfbd400363d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-number&quot;)</value>
      <webElementGuid>535c7256-abf1-4a50-8533-d09579fc4e2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id-number']</value>
      <webElementGuid>2c3d387f-2919-476b-94ec-d05f32422822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/div/div/div[2]/div/div/div[2]/div/form/div[4]/input</value>
      <webElementGuid>d3be4ebb-6c3e-49cd-ae1d-e9d443d9f64c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>138a95b5-dd59-4224-9b7d-2b5c5971a250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'govId' and @placeholder = 'EG : A12345678' and @type = 'text' and @id = 'id-number']</value>
      <webElementGuid>3d57471a-4de6-4cba-bd1a-4da672784d46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
