<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Plate Number</name>
   <tag></tag>
   <elementGuidId>f7fc8461-ae2f-4870-9199-a0dbb1103092</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vehicle-registration-number</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@placeholder = 'EG : ABC1234' and @name = 'plateNumber' and @type = 'text' and @id = 'vehicle-registration-number' and @class = 'textfield-height  form-control']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vehicle-registration-number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;EG : ABC1234&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64982325-3776-45a6-b612-aa93304adf8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>EG : ABC1234</value>
      <webElementGuid>b28d0a79-b1c7-4545-b83d-83032bb632ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0a540025-85e2-4441-9afd-1ddf4cd71b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>0d82d2f6-b633-49d4-9a7e-efc39c340c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>plateNumber</value>
      <webElementGuid>d46ef76d-730b-4288-8e40-01c73ef7da69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>63bb735f-d054-4601-9f45-3043194f662b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vehicle-registration-number</value>
      <webElementGuid>b9a0adf1-29be-45d7-8952-5d2b67361a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield-height  form-control</value>
      <webElementGuid>8c18ef7c-005c-46bc-babd-0f7e6630cd40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vehicle-registration-number&quot;)</value>
      <webElementGuid>f4b3798f-d85a-4500-b95c-a33a1cf1fac4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vehicle-registration-number']</value>
      <webElementGuid>f70d32f2-d0a5-4f62-a9f1-510f59e4caca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/div/div/div[2]/div/div/div[2]/div/form/div/input</value>
      <webElementGuid>790aaa27-5d91-430f-959f-a842111c73b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3fe40317-64e1-4d61-9d4b-4fb5f705949d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'EG : ABC1234' and @name = 'plateNumber' and @type = 'text' and @id = 'vehicle-registration-number']</value>
      <webElementGuid>36cb1d56-dc92-410a-8a02-a935e654547c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
