<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NRIC</name>
   <tag></tag>
   <elementGuidId>53427f75-7741-4f84-9e3b-7cfa35fa338a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id-number</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'govId' and @placeholder = 'EG : 900719082777' and @type = 'text' and @id = 'id-number' and @class = 'textfield-height undefined form-control']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id-number']/preceding-sibling::label[text()='NRIC Number']/following-sibling::input[@id='id-number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;EG : 900719082777&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4d5ffbc-3c41-4eb9-81fd-8a9be91c9fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3d4dd93f-e04a-4def-bc85-8316a0f69cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>f20c376c-9ff1-4c09-aec9-c12b8976bf4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>govId</value>
      <webElementGuid>8a394a56-b4da-4265-94f8-520e539fe9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>EG : 900719082777</value>
      <webElementGuid>909f10d7-b081-4224-875e-6cb847300a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c82ce170-3a6a-47f6-9543-9e8fc61b89ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id-number</value>
      <webElementGuid>cfe63cfc-8773-4d4d-8abe-bf740f54ba9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield-height undefined form-control</value>
      <webElementGuid>f0cd29ba-20d1-4589-80f5-2dd847c63619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-number&quot;)</value>
      <webElementGuid>968c4a4c-9925-4b71-9ad2-a2eb05f204c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id-number']</value>
      <webElementGuid>0dc90acb-ead0-43ac-8677-7a68a95d8877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/div/div/div[2]/div/div/div[2]/div/form/div[4]/input</value>
      <webElementGuid>ddc787f7-64cc-42bd-8694-c0beae4e9bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>7a62e28f-aad5-4492-9b9e-99c7b6086558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'govId' and @placeholder = 'EG : 900719082777' and @type = 'text' and @id = 'id-number']</value>
      <webElementGuid>e20b8a40-8da6-40e2-b16d-b2ee07eedb76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
