<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date Of Birth</name>
   <tag></tag>
   <elementGuidId>bbb0e00d-140d-4f48-a8d9-d2e84d483ccb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form-input-dob</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'dob' and @placeholder = 'e.g. 21/03/1978' and @type = 'text' and @id = 'form-input-dob']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='form-input-dob']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;e.g. 21/03/1978&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aafb5387-f6d6-476b-b5dc-77f86a93a171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dob</value>
      <webElementGuid>f82bdfbd-b345-4496-95a7-4a9252c0812c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. 21/03/1978</value>
      <webElementGuid>ddece2ba-5943-49a9-858d-0b1b8e62692c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>29415781-3a0c-4d2c-b235-1a516ce314c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>debd8c61-c847-4929-9d7a-2b0601eb8463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9872ac63-0b8d-4794-a0b0-0a7582c2e7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form-input-dob</value>
      <webElementGuid>617eacf5-3575-4f56-8696-80195b482390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield-height text-uppercase form-control</value>
      <webElementGuid>6643eaa9-5974-48ba-8419-9b06c5e26ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-input-dob&quot;)</value>
      <webElementGuid>0b8b3a7b-195e-429c-be96-f2c178720006</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form-input-dob']</value>
      <webElementGuid>f2800e44-0b5f-4366-b253-be29f66b6a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/div/div/div[2]/div/div/div[2]/div/form/div[6]/input</value>
      <webElementGuid>1f3436eb-9e07-4373-ae66-841f5c1e78d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>c043764b-6e24-404c-a196-76786a507f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'dob' and @placeholder = 'e.g. 21/03/1978' and @type = 'text' and @id = 'form-input-dob']</value>
      <webElementGuid>af342f81-d35b-4b2c-91b0-8323145a8fa5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
