<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Police ID Number</name>
   <tag></tag>
   <elementGuidId>edfd0361-3e00-4101-9850-c612d571bb13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#secondary-id-number</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'secondaryIdentityNumber' and @placeholder = 'EG : N/123456' and @type = 'text' and @id = 'secondary-id-number']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='secondary-id-number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;EG : N/123456&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9495edd5-0a92-4bac-89c5-2a3db8ea1502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b8e523c4-9329-4692-8fd9-d1ed0bd9ba0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>254d39b1-9e3b-4fb7-aa2b-8ec81259c4f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>secondaryIdentityNumber</value>
      <webElementGuid>56705b38-5d85-435f-933a-bee2c4ee7a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>EG : N/123456</value>
      <webElementGuid>3a394e9e-2bf7-4787-b24e-f147c3d1dd6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>45839f5e-89ea-4df6-b491-d23cdae65cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondary-id-number</value>
      <webElementGuid>a093e891-6fa7-45b7-8e3f-26b0c1a30b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield-height  form-control</value>
      <webElementGuid>acdfafaa-582b-4e4e-a8d8-dba12809a482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondary-id-number&quot;)</value>
      <webElementGuid>ab395c82-ddcd-4661-890b-7745acddcb3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='secondary-id-number']</value>
      <webElementGuid>bf4f189f-7fe4-4670-8434-98d6afdd7631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/div/div/div[2]/div/div/div[2]/div/form/div[5]/input</value>
      <webElementGuid>22cf4286-6ed8-4806-ad9b-e3fdb7d8408d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>84f97da2-1323-49ea-ad7c-0acd13102d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'secondaryIdentityNumber' and @placeholder = 'EG : N/123456' and @type = 'text' and @id = 'secondary-id-number']</value>
      <webElementGuid>c9f1808c-579c-4686-b728-c1870d9eb2b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
