<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Army ID Number</name>
   <tag></tag>
   <elementGuidId>5fcd809d-ec12-4ef5-99bb-1142fdf77067</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#secondary-id-number</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'secondaryIdentityNumber' and @placeholder = 'EG : RF/123456' and @type = 'text' and @id = 'secondary-id-number']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='secondary-id-number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;EG : RF/123456&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb2d10c4-840c-4ac7-81aa-2a50492e6499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>674f397c-231f-4a9d-abe3-ab0ae44a4caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>3c90ea86-bfa0-415e-8087-11676d80a3c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>secondaryIdentityNumber</value>
      <webElementGuid>a1788bf0-cf12-41dd-9272-d0465fdbcc88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>EG : RF/123456</value>
      <webElementGuid>34c9f018-e6a2-4bc6-bca9-3b13bbc7a608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>21ca4acb-575e-4258-88d5-fc5d01fc2c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondary-id-number</value>
      <webElementGuid>08424d36-d6ff-46d4-9ed1-df01f2c26f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textfield-height  form-control</value>
      <webElementGuid>67f754ac-62df-49bc-8f14-409a3ee67cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondary-id-number&quot;)</value>
      <webElementGuid>905f9c28-b4ca-4069-a497-b7c513b7d42e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='secondary-id-number']</value>
      <webElementGuid>c305b36f-d7f1-4807-bf89-34b42ec03383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/div/div/div[2]/div/div/div[2]/div/form/div[5]/input</value>
      <webElementGuid>708de7ac-7386-4f36-8839-ab10dcdc976a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>548f34d4-342f-4ac4-91ff-62ff263d518f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'secondaryIdentityNumber' and @placeholder = 'EG : RF/123456' and @type = 'text' and @id = 'secondary-id-number']</value>
      <webElementGuid>5a782138-dcb7-4aab-9a39-98878a95187e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
