<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wrnmsg_IDPolice</name>
   <tag></tag>
   <elementGuidId>a90134db-d1ac-4508-99f0-d275a663a1a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[contains(text(), 'ID Number')]//following-sibling::p[@class='text-danger']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>2eaf46dc-4993-4972-be4c-7965703e7027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1734939545988</value>
      <webElementGuid>7f67b9e6-fab1-4d01-9593-5f680eb97150</webElementGuid>
   </webElementProperties>
</WebElementEntity>
