<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wrnmsg_NRIC</name>
   <tag></tag>
   <elementGuidId>022bbad7-e0d1-4fb8-b7ac-e5c1acbe3210</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[contains(text(), 'NRIC')]//following-sibling::p[@class='text-danger']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>05d75557-db52-4fd9-9940-21999baae94c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1734939545688</value>
      <webElementGuid>1e740e67-9f48-4bf7-9965-076ebece02f7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
