<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wrnmsg_IDArmy</name>
   <tag></tag>
   <elementGuidId>8325bedb-dd46-40b5-afda-b5fe673563de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[contains(text(), 'ID Number')]//following-sibling::p[@class='text-danger']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>1e1c446a-4ffb-40bd-9a22-c03937f61876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1734939545844</value>
      <webElementGuid>fd2eadd7-cdcb-4b50-bd7f-3d8effb0b15b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
