<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dyvalidation_PolicyNumber_text,code</name>
   <tag></tag>
   <elementGuidId>8a02d100-6b90-4139-89d9-1570b22a575f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='${text}']//following-sibling::div[contains(text(), '${code}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.status__DotBox-sc-17j7umb-2.vBkoF</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e009a124-d2fb-4f56-b3d5-d118daa85e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>status__DotBox-sc-17j7umb-2 vBkoF</value>
      <webElementGuid>fb56ea4f-ec86-4702-9a95-e7444748a7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Policy NumberPU002476</value>
      <webElementGuid>c281c846-3d6c-4b9c-84a4-1d6640e69207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;Layout__Styles-sc-d7vu2k-0 fGSPvF&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;justify-content-center row&quot;]/div[@class=&quot;col-md-3 col-6&quot;]/div[@class=&quot;status__DotBox-sc-17j7umb-2 vBkoF&quot;]</value>
      <webElementGuid>9e2f050f-fff7-4371-ba59-62408fd61266</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div[2]/div/div/div</value>
      <webElementGuid>b56f474e-2517-4624-981c-317a6656db7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[1]/following::div[10]</value>
      <webElementGuid>8de76102-34d0-4fb3-92d2-564285041e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div</value>
      <webElementGuid>b3188f62-0e66-4413-a2e5-0542f1603788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Policy NumberPU002476' or . = 'Policy NumberPU002476')]</value>
      <webElementGuid>722db943-6134-4503-86a9-00c2178cb30a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
