<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dyvalidation_TransactionSummary_title,code</name>
   <tag></tag>
   <elementGuidId>8a02d100-6b90-4139-89d9-1570b22a575f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='${title}']//following-sibling::div[contains(text(), '${code}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.status__DotBox-sc-17j7umb-2.vBkoF</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a259a3db-e23c-40f3-aa0f-3fbb16e027db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>status__DotBox-sc-17j7umb-2 vBkoF</value>
      <webElementGuid>ae5a07d1-a193-4c15-9f59-efd9dcba5e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Policy NumberPU002476</value>
      <webElementGuid>2f9c97f7-9aa4-4d84-bd5b-59f50d140bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;Layout__Styles-sc-d7vu2k-0 fGSPvF&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;justify-content-center row&quot;]/div[@class=&quot;col-md-3 col-6&quot;]/div[@class=&quot;status__DotBox-sc-17j7umb-2 vBkoF&quot;]</value>
      <webElementGuid>c67d5819-1bcf-4a45-8e96-6295e397a7a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div[2]/div/div/div</value>
      <webElementGuid>ab1c5a67-5662-48ea-8aa5-a92f82a67006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[1]/following::div[10]</value>
      <webElementGuid>6c7a6db7-3c1f-45bd-b3a3-b0cbcf4f9d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div</value>
      <webElementGuid>47b97502-03a5-47fc-ab5a-3879c68d664b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Policy NumberPU002476' or . = 'Policy NumberPU002476')]</value>
      <webElementGuid>5f06bec6-30a8-48bb-a301-3c137714d27c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
