<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UserId</name>
   <tag></tag>
   <elementGuidId>8f533d2d-069b-40b7-9a4a-f101726d393a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#userId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='userId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6e1cd0f-1c2a-49a3-bec8-8800e0965c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2b0681d8-0d7d-4f7c-b64c-df95e49e3b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userId</value>
      <webElementGuid>53a25f1f-179c-4959-a865-693da33a3473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CardNum</value>
      <webElementGuid>834c4f36-25d2-4dbb-b098-0203ef6d13bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>181a7e57-bb7c-4ea5-9dc6-59b68832f4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>User Id</value>
      <webElementGuid>a948632f-1471-44e5-8be5-fda4a8c68b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userId&quot;)</value>
      <webElementGuid>44eeb541-b4a7-4bfe-b29e-3fe8865351ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='userId']</value>
      <webElementGuid>b9959242-d094-45c2-8b33-008034437fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>025a44ea-6e9f-4f40-b5fb-66f158b723d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'userId' and @name = 'CardNum' and @placeholder = 'User Id']</value>
      <webElementGuid>c28cfc22-ac81-4106-8e33-9beed706f3a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
