<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>validation_YourPaymentIsSuccessful</name>
   <tag></tag>
   <elementGuidId>1b08a2c1-6a9a-4cd8-a775-1885f38f9ba8</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h4.PaymentStatusHeader__SuccessTitle-sc-q2uo8o-2.dUuAQo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h4[@class='PaymentStatusHeader__SuccessTitle-sc-q2uo8o-2 dUuAQo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>b7eeb589-b366-4f69-ab14-edf243745fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PaymentStatusHeader__SuccessTitle-sc-q2uo8o-2 dUuAQo</value>
      <webElementGuid>8e4994c8-8427-4a54-9bb2-9590d246691c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Your Payment is Successful</value>
      <webElementGuid>85c8c05b-de6a-480d-a429-bc65dcca24af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;Layout__Styles-sc-d7vu2k-0 fGSPvF&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;text-center col&quot;]/h4[@class=&quot;PaymentStatusHeader__SuccessTitle-sc-q2uo8o-2 dUuAQo&quot;]</value>
      <webElementGuid>06543ff9-50ad-4bdd-a41e-7b747bf49ba3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div[2]/div/div/div/h4</value>
      <webElementGuid>39ed1928-13e9-4d61-9280-28393bc08491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EN'])[1]/following::h4[1]</value>
      <webElementGuid>7ec8759b-f99a-4252-9f1e-62f5d787b3d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Policy Number'])[1]/preceding::h4[1]</value>
      <webElementGuid>9b2ae15f-8379-485b-9fb4-d93279bda671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PU002476'])[1]/preceding::h4[1]</value>
      <webElementGuid>811d4b4b-0e4b-442d-b3a3-f2979fae940e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your Payment is Successful']/parent::*</value>
      <webElementGuid>8f672b64-9f78-4f59-ad34-586a25f7b69a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>89861465-ee80-4431-a493-f2c0fed65b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = ' Your Payment is Successful' or . = ' Your Payment is Successful')]</value>
      <webElementGuid>3bdc7ed8-6e2e-431c-afe3-8b60b7e6f904</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
