name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v4.0
      with:
          version: '9.7.3'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -browserType=Chrome -statusDelay=15 -testSuiteCollectionPath="Test Suites/TestSuiteCollection/Travel" -apiKey= ${{ secrets.KATALON_API_KEY }} --config -webui.autoUpdateDrivers=true'