<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dywrnmsg_TravellerInfo_travellerInfo</name>
   <tag></tag>
   <elementGuidId>535a2669-1596-4911-9312-6cd32f666744</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//label[contains(text(),'${travellerInfo}')])[1]/following-sibling::p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>78a76970-de54-4c61-a4b9-0553cd5d5153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1733282995137</value>
      <webElementGuid>48eea08c-7b4d-4986-8220-ebfe1fa30c8e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
