<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wrnmsg_Postcode</name>
   <tag></tag>
   <elementGuidId>535a2669-1596-4911-9312-6cd32f666744</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Postcode'])[1]/following-sibling::p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>8c33b0ef-4d5a-4f2b-8667-67ecc9ab06a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1733282995137</value>
      <webElementGuid>07f8c1c6-9336-4c2a-87aa-3043dc29de19</webElementGuid>
   </webElementProperties>
</WebElementEntity>
